import React from 'react';
import AnalyticsMetricCard from './AnalyticsMetricCard.jsx';
import AnalyticsTrend from './AnalyticsTrend.jsx';
import { formatChange, formatMoney, formatNumber, titleCase } from '../teamAnalyticsHelpers.js';

const StatusList = ({ title, values }) => <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-slate-950">{title}</h3><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(values || {}).map(([key, value]) => <div key={key} className="rounded-lg bg-slate-50 px-3 py-2"><p className="text-xs text-slate-500">{titleCase(key)}</p><p className="mt-1 font-semibold tabular-nums text-slate-900">{formatNumber(value)}</p></div>)}</div></section>;

const MarketingAnalytics = ({ data }) => {
  const summary = data.summary || {};
  return <div className="space-y-7"><section><h3 className="mb-3 text-sm font-semibold text-slate-950">Marketing activity</h3><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><AnalyticsMetricCard label="Campaigns created" value={formatNumber(summary.campaignsCreated)}/><AnalyticsMetricCard label="Campaigns worked on" value={formatNumber(summary.campaignsWorkedOn)}/><AnalyticsMetricCard label="Campaign actions" value={formatNumber(summary.campaignActions)}/><AnalyticsMetricCard label="Banners created" value={formatNumber(summary.bannersCreated)}/><AnalyticsMetricCard label="Banners worked on" value={formatNumber(summary.bannersWorkedOn)}/><AnalyticsMetricCard label="Banner actions" value={formatNumber(summary.bannerActions)}/><AnalyticsMetricCard label="Active campaigns authored" value={formatNumber(summary.activeCampaignsAuthored)}/><AnalyticsMetricCard label="Scheduled campaigns" value={formatNumber(summary.scheduledCampaigns)}/><AnalyticsMetricCard label="Completed campaigns" value={formatNumber(summary.completedCampaigns)}/><AnalyticsMetricCard label="Active promotions" value={formatNumber(summary.activePromotions)}/><AnalyticsMetricCard label="Scheduled promotions" value={formatNumber(summary.scheduledPromotions)}/><AnalyticsMetricCard label="Total marketing actions" value={formatNumber(summary.totalMarketingActions)} hint={formatChange(data.comparisons?.totalMarketingActions)}/><AnalyticsMetricCard label="Configured campaign budget" value={formatMoney(summary.configuredCampaignBudget)} hint="Configured budget, not verified ad spend"/></div></section><div className="grid gap-5 xl:grid-cols-2"><StatusList title="Campaign status breakdown" values={data.breakdowns?.campaigns}/><StatusList title="Promotion status breakdown" values={data.breakdowns?.banners}/></div>{data.dataAvailability?.impactTrackingAvailable === false && <section className="rounded-xl border border-amber-200 bg-amber-50 px-5 py-4"><h3 className="text-sm font-semibold text-amber-950">Impact tracking is not configured yet.</h3><p className="mt-1 text-sm text-amber-800">{data.dataAvailability.impactTrackingReason}</p></section>}<AnalyticsTrend data={data.trend} keys={[{ value: 'campaignActions', label: 'Campaign actions', color: 'bg-emerald-500' }, { value: 'bannerActions', label: 'Banner actions', color: 'bg-blue-500' }, { value: 'recordsActivated', label: 'Status changes', color: 'bg-violet-500' }]}/></div>;
};

export default MarketingAnalytics;
