import React from 'react';
import AnalyticsMetricCard from './AnalyticsMetricCard.jsx';
import AnalyticsTrend from './AnalyticsTrend.jsx';
import { formatChange, formatDuration, formatMoney, formatNumber, formatPercent, titleCase } from '../teamAnalyticsHelpers.js';

const Section = ({ title, description, children }) => <section><div className="mb-3"><h3 className="text-sm font-semibold text-slate-950">{title}</h3>{description && <p className="mt-1 text-xs text-slate-500">{description}</p>}</div>{children}</section>;
const Distribution = ({ title, values = {} }) => <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-slate-950">{title}</h3><div className="mt-4 space-y-3">{Object.entries(values).length ? Object.entries(values).map(([key, value]) => <div key={key} className="flex items-center justify-between gap-4 text-sm"><span className="text-slate-600">{titleCase(key)}</span><span className="font-semibold tabular-nums text-slate-900">{formatNumber(value)}</span></div>) : <p className="text-sm text-slate-500">No activity recorded for this period.</p>}</div></section>;

const SalesAnalytics = ({ data }) => {
  const summary = data.summary || {};
  const breakdowns = data.breakdowns || {};
  const quote = breakdowns.quotations || {};
  return <div className="space-y-7">
    <Section title="Customer activity" description="Expert Requests are shared; these figures use actions logged by this member."><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><AnalyticsMetricCard label="Unique travelers contacted" value={formatNumber(summary.uniqueTravelersContacted)}/><AnalyticsMetricCard label="Contact actions" value={formatNumber(summary.contactActions)} hint={`${formatNumber(breakdowns.channels?.calls)} calls · ${formatNumber(breakdowns.channels?.whatsapp)} WhatsApp · ${formatNumber(breakdowns.channels?.email)} email${formatChange(data.comparisons?.contactActions) ? ` · ${formatChange(data.comparisons.contactActions)}` : ""}`}/><AnalyticsMetricCard label="Connected conversations" value={formatNumber(summary.connectedConversations)}/><AnalyticsMetricCard label="Connection rate" value={formatPercent(summary.connectionRate)} hint="Connected ÷ call-style outcomes"/></div></Section>
    <div className="grid gap-5 xl:grid-cols-2"><Distribution title="Outcome breakdown" values={breakdowns.outcomes}/><Distribution title="Leads touched — current stage" values={breakdowns.stages}/></div>
    <Section title="Follow-ups"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-7"><AnalyticsMetricCard label="Created" value={formatNumber(breakdowns.followUps?.created)}/><AnalyticsMetricCard label="Completed" value={formatNumber(breakdowns.followUps?.completed)}/><AnalyticsMetricCard label="Pending" value={formatNumber(breakdowns.followUps?.pending)}/><AnalyticsMetricCard label="Overdue" value={formatNumber(breakdowns.followUps?.overdue)}/><AnalyticsMetricCard label="Cancelled" value={formatNumber(breakdowns.followUps?.cancelled)}/><AnalyticsMetricCard label="Rescheduled" value={formatNumber(breakdowns.followUps?.rescheduled)}/><AnalyticsMetricCard label="Completion rate" value={formatPercent(breakdowns.followUps?.completionRate)} hint="Completed ÷ created"/></div></Section>
    <Section title="Sales outcomes" description="Assisted results and primary quotation attribution are intentionally separate."><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><AnalyticsMetricCard label="Unique leads touched" value={formatNumber(summary.uniqueLeadsTouched)}/><AnalyticsMetricCard label="Assisted conversions" value={formatNumber(summary.assistedConversions)} hint="Non-exclusive shared-queue contribution"/><AnalyticsMetricCard label="Quotations created" value={formatNumber(summary.quotationsCreated)}/><AnalyticsMetricCard label="Bookings generated" value={formatNumber(summary.bookingsGenerated)} hint="Source quotation created by this member"/><AnalyticsMetricCard label="Paid customers" value={formatNumber(summary.paidCustomers)}/><AnalyticsMetricCard label="Paid revenue attributed" value={formatMoney(summary.paidRevenue)} hint="Collected amount only"/><AnalyticsMetricCard label="Booking value generated" value={formatMoney(summary.bookingValue)} hint="Separate from collected revenue"/><AnalyticsMetricCard label="Average first response" value={formatDuration(breakdowns.averageFirstResponseMs)} hint={`${formatNumber(breakdowns.firstResponseLeadCount)} first-actor leads`}/></div></Section>
    <Section title="Quotation activity"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><AnalyticsMetricCard label="Revisions created" value={formatNumber(quote.revisionsCreated)}/><AnalyticsMetricCard label="Shares created" value={formatNumber(quote.sharesCreated)}/><AnalyticsMetricCard label="Customer views" value={formatNumber(quote.customerViews)}/><AnalyticsMetricCard label="Customer approvals" value={formatNumber(quote.customerApprovals)}/><AnalyticsMetricCard label="Change requests" value={formatNumber(quote.changeRequests)}/><AnalyticsMetricCard label="Quotation → booking" value={formatPercent(quote.quotationToBookingRate)} hint="Bookings generated ÷ quotations created"/><AnalyticsMetricCard label="Assisted lead conversion" value={formatPercent(quote.assistedLeadConversionRate)} hint="Assisted conversions ÷ unique leads touched"/></div></Section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><AnalyticsTrend data={data.trend} keys={[{ value: 'contacts', label: 'Contacts', color: 'bg-emerald-500' }, { value: 'followUpsCompleted', label: 'Follow-ups', color: 'bg-blue-500' }, { value: 'quotations', label: 'Quotations', color: 'bg-violet-500' }, { value: 'bookings', label: 'Bookings', color: 'bg-amber-500' }]}/><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-slate-950">Top destinations handled</h3><div className="mt-4 space-y-3">{breakdowns.topDestinations?.length ? breakdowns.topDestinations.map((item) => <div key={item._id} className="flex justify-between gap-3 text-sm"><span className="truncate text-slate-600">{item._id}</span><strong className="tabular-nums text-slate-900">{item.count}</strong></div>) : <p className="text-sm text-slate-500">No destinations recorded.</p>}</div></section></div>
  </div>;
};

export default SalesAnalytics;
