import React, { useEffect, useState } from 'react';
import { ArrowLeft, ImagePlus, Plus, Save, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import MediaLibraryModal from '../../../../components/MediaLibraryModal.jsx';
import UploadLocationImageModal from '../../../../components/UploadLocationImageModal.jsx';
import { createHotelApi, getHotelApi, listHotelVendorsApi, setHotelStatusApi, updateHotelApi } from '../../../../services/hotelService.js';

const types = ['HOTEL', 'BOUTIQUE_HOTEL', 'RESORT', 'HOSTEL', 'HOMESTAY', 'GUEST_HOUSE', 'CAMP', 'VILLA', 'APARTMENT', 'LODGE', 'OTHER'];
const mealPlans = ['EP', 'CP', 'MAP', 'AP'];
const sections = ['Basic', 'Location', 'Stay', 'Rooms', 'Media', 'Contact & Vendor', 'Commercial', 'Review'];
const empty = { name: '', aliases: [], propertyType: 'HOTEL', starRating: 0, classification: '', tags: [], shortDescription: '', description: '', location: { city: '', country: 'India' }, stayInfo: {}, amenities: [], highlights: [], roomTypes: [], availableMealPlans: [], ratePlans: [], media: { hero: null, gallery: [] }, contact: {}, vendorId: null, internalNotes: '', catalogVersion: 1, status: 'DRAFT' };
const inputStyle = 'mt-1 w-full min-h-10 rounded border border-slate-300 bg-white px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none disabled:bg-slate-50';
const Button = ({ children, ...props }) => <button type="button" {...props} className={`inline-flex min-h-9 items-center gap-2 rounded border border-slate-300 px-3 text-sm font-medium text-slate-700 disabled:opacity-40 ${props.className || ''}`}>{children}</button>;
const Field = ({ label, value, onChange, type = 'text', required = false, ...props }) => <label className="block text-sm font-medium text-slate-700">{label}{required && ' *'}<input type={type} value={value ?? ''} onChange={(event) => onChange(type === 'number' ? Number(event.target.value) : event.target.value)} required={required} {...props} className={inputStyle} /></label>;
const Area = ({ label, value, onChange }) => <label className="block text-sm font-medium text-slate-700">{label}<textarea value={value || ''} onChange={(event) => onChange(event.target.value)} className={`${inputStyle} min-h-24`} /></label>;
const List = ({ label, value, onChange }) => <Area label={label} value={(value || []).join('\n')} onChange={(text) => onChange(text.split('\n').map((item) => item.trim()).filter(Boolean))} />;

export default function HotelEditor({ readOnly = false }) {
  const { id } = useParams();
  const navigate = useNavigate();
  const [hotel, setHotel] = useState(empty);
  const [section, setSection] = useState('Basic');
  const [loading, setLoading] = useState(Boolean(id));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [vendors, setVendors] = useState([]);
  const [mediaTarget, setMediaTarget] = useState(null);
  const [uploadOpen, setUploadOpen] = useState(false);
  const locked = readOnly || hotel.status === 'ARCHIVED';
  const change = (key, value) => setHotel((current) => ({ ...current, [key]: value }));
  const nested = (key, name, value) => setHotel((current) => ({ ...current, [key]: { ...(current[key] || {}), [name]: value } }));
  const roomChange = (index, name, value) => change('roomTypes', hotel.roomTypes.map((room, i) => i === index ? { ...room, [name]: value } : room));
  const rateChange = (index, name, value) => change('ratePlans', hotel.ratePlans.map((rate, i) => i === index ? { ...rate, [name]: value } : rate));
  useEffect(() => {
    let alive = true;
    if (id) getHotelApi(id).then((data) => { if (alive) setHotel(data.data); }).catch((cause) => { if (alive) setError(cause.message); }).finally(() => { if (alive) setLoading(false); });
    listHotelVendorsApi().then((data) => { if (alive) setVendors(data); }).catch(() => {});
    return () => { alive = false; };
  }, [id]);
  const save = async () => {
    setSaving(true); setError(''); setNotice('');
    try {
      const result = id ? await updateHotelApi(id, hotel) : await createHotelApi(hotel);
      setHotel(result.data);
      if (!id) navigate(`/staff/admin/hotels/${result.data._id}/edit`, { replace: true });
      setNotice('Hotel saved.');
    } catch (cause) { setError(cause.message); }
    finally { setSaving(false); }
  };
  const status = async (next) => {
    if (next === 'ARCHIVED' && !window.confirm('Archive this hotel? Historical quotations will remain unchanged.')) return;
    setSaving(true); setError('');
    try { const result = await setHotelStatusApi(id, next, hotel.catalogVersion); setHotel(result.data); setNotice(`Hotel is now ${next.toLowerCase()}.`); }
    catch (cause) { setError(cause.message); }
    finally { setSaving(false); }
  };
  const chooseMedia = (media) => {
    const item = { assetId: media.assetId, secureUrl: media.url, altText: media.altText, caption: media.caption };
    if (mediaTarget === 'hero') nested('media', 'hero', item);
    if (mediaTarget === 'gallery' && (hotel.media?.gallery || []).length < 12) nested('media', 'gallery', [...(hotel.media?.gallery || []), item]);
    if (mediaTarget?.type === 'room') {
      const room = hotel.roomTypes[mediaTarget.index];
      if (room && (room.media || []).length < 8) roomChange(mediaTarget.index, 'media', [...(room.media || []), item]);
    }
    setMediaTarget(null);
  };
  const activationIssues = [!hotel.name?.trim() && 'name', !hotel.location?.city?.trim() && 'city', !hotel.location?.country?.trim() && 'country', !hotel.media?.hero?.assetId && 'hero image', !(hotel.roomTypes || []).some((room) => room.active && room.name?.trim()) && 'active room', !hotel.availableMealPlans?.length && 'meal plan'].filter(Boolean);
  if (loading) return <div className="py-16 text-center text-sm text-slate-500">Loading hotel…</div>;
  return <div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 pb-5"><div><Link to="/staff/admin/hotels" className="inline-flex items-center gap-1 text-sm text-slate-600"><ArrowLeft size={15} />Hotels</Link><h1 className="mt-2 text-2xl font-semibold text-slate-950">{id ? hotel.name || 'Hotel' : 'New hotel'}</h1><p className="mt-1 text-sm text-slate-500">{hotel.hotelCode || 'Draft property'} · {hotel.status}</p></div><div className="flex gap-2">{readOnly && hotel.status !== 'ARCHIVED' && <Link to={`/staff/admin/hotels/${id}/edit`} className="rounded bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Edit hotel</Link>}{!locked && <button type="button" onClick={save} disabled={saving} className="inline-flex min-h-10 items-center gap-2 rounded bg-slate-950 px-4 text-sm font-semibold text-white disabled:opacity-50"><Save size={16} />{saving ? 'Saving…' : 'Save draft'}</button>}</div></header>
    {error && <div role="alert" className="border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}{notice && <div role="status" className="border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}
    <nav aria-label="Hotel sections" className="flex gap-1 overflow-x-auto border-b border-slate-200">{sections.map((name) => <button key={name} type="button" onClick={() => setSection(name)} className={`shrink-0 border-b-2 px-3 py-2 text-sm ${section === name ? 'border-emerald-600 font-semibold text-emerald-700' : 'border-transparent text-slate-600'}`}>{name}</button>)}</nav>
    <fieldset disabled={locked || saving} className="space-y-5">
      {section === 'Basic' && <div className="grid gap-4 md:grid-cols-2"><Field label="Property name" value={hotel.name} onChange={(value) => change('name', value)} required /><label className="text-sm font-medium text-slate-700">Property type<select value={hotel.propertyType} onChange={(event) => change('propertyType', event.target.value)} className={inputStyle}>{types.map((type) => <option key={type} value={type}>{type.replaceAll('_', ' ')}</option>)}</select></label><Field label="Star rating" type="number" min="0" max="5" value={hotel.starRating} onChange={(value) => change('starRating', value)} /><Field label="Classification" value={hotel.classification} onChange={(value) => change('classification', value)} /><div className="md:col-span-2"><List label="Aliases (one per line)" value={hotel.aliases} onChange={(value) => change('aliases', value)} /></div><div className="md:col-span-2"><List label="Tags (one per line)" value={hotel.tags} onChange={(value) => change('tags', value)} /></div><div className="md:col-span-2"><Area label="Short description" value={hotel.shortDescription} onChange={(value) => change('shortDescription', value)} /></div><div className="md:col-span-2"><Area label="Description" value={hotel.description} onChange={(value) => change('description', value)} /></div></div>}
      {section === 'Location' && <div className="grid gap-4 md:grid-cols-2">{['addressLine1', 'addressLine2', 'locality', 'city', 'state', 'country', 'pincode'].map((key) => <Field key={key} label={key.replace(/([A-Z])/g, ' $1')} value={hotel.location?.[key]} onChange={(value) => nested('location', key, value)} required={['city', 'country'].includes(key)} />)}<Field label="Latitude" type="number" min="-90" max="90" step="any" value={hotel.location?.coordinates?.lat} onChange={(value) => nested('location', 'coordinates', { ...hotel.location?.coordinates, lat: value })} /><Field label="Longitude" type="number" min="-180" max="180" step="any" value={hotel.location?.coordinates?.lng} onChange={(value) => nested('location', 'coordinates', { ...hotel.location?.coordinates, lng: value })} /><div className="md:col-span-2"><List label="Nearby landmarks" value={hotel.location?.nearbyLandmarks} onChange={(value) => nested('location', 'nearbyLandmarks', value)} /></div></div>}
      {section === 'Stay' && <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2">{['checkInTime', 'checkOutTime', 'earlyCheckInNotes', 'lateCheckOutNotes', 'childPolicy', 'extraBedPolicy', 'propertyNotes'].map((key) => <Field key={key} label={key.replace(/([A-Z])/g, ' $1')} value={hotel.stayInfo?.[key]} onChange={(value) => nested('stayInfo', key, value)} />)}</div><List label="Amenities" value={hotel.amenities} onChange={(value) => change('amenities', value)} /><List label="Highlights" value={hotel.highlights} onChange={(value) => change('highlights', value)} /><div><p className="mb-2 text-sm font-medium text-slate-700">Available meal plans</p><div className="flex flex-wrap gap-4">{mealPlans.map((plan) => <label key={plan} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={hotel.availableMealPlans?.includes(plan) || false} onChange={(event) => change('availableMealPlans', event.target.checked ? [...hotel.availableMealPlans, plan] : hotel.availableMealPlans.filter((value) => value !== plan))} />{plan}</label>)}</div></div></div>}
      {section === 'Rooms' && <div className="space-y-4"><Button disabled={locked} onClick={() => change('roomTypes', [...hotel.roomTypes, { name: '', description: '', bedType: '', maxOccupancy: 2, maxAdults: 2, maxChildren: 0, extraBedAllowed: false, amenities: [], media: [], active: true }])}><Plus size={15} />Add room type</Button>{hotel.roomTypes.map((room, index) => <div key={room.roomTypeId || index} className="border-t border-slate-200 pt-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-slate-900">{room.name || `Room ${index + 1}`}</h2><Button aria-label={`Remove ${room.name || 'room'}`} onClick={() => change('roomTypes', hotel.roomTypes.filter((_, i) => i !== index))}><Trash2 size={15} /></Button></div><div className="grid gap-4 md:grid-cols-3"><Field label="Room name" value={room.name} onChange={(value) => roomChange(index, 'name', value)} required /><Field label="Bed type" value={room.bedType} onChange={(value) => roomChange(index, 'bedType', value)} /><Field label="Max occupancy" type="number" min="1" value={room.maxOccupancy} onChange={(value) => roomChange(index, 'maxOccupancy', value)} /><Field label="Max adults" type="number" min="1" value={room.maxAdults} onChange={(value) => roomChange(index, 'maxAdults', value)} /><Field label="Max children" type="number" min="0" value={room.maxChildren} onChange={(value) => roomChange(index, 'maxChildren', value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={room.extraBedAllowed || false} onChange={(event) => roomChange(index, 'extraBedAllowed', event.target.checked)} />Extra bed allowed</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={room.active !== false} onChange={(event) => roomChange(index, 'active', event.target.checked)} />Active</label><div className="md:col-span-3"><Area label="Description" value={room.description} onChange={(value) => roomChange(index, 'description', value)} /></div><div className="md:col-span-3"><List label="Room amenities" value={room.amenities} onChange={(value) => roomChange(index, 'amenities', value)} /></div></div></div>)}</div>}
      {section === 'Rooms' && hotel.roomTypes.map((room, index) => <section key={`media-${room.roomTypeId || index}`} className="border-t border-slate-200 pt-4"><h2 className="text-sm font-semibold text-slate-900">{room.name || `Room ${index + 1}`} media</h2><div className="mt-2 flex flex-wrap gap-2">{(room.media || []).map((item, mediaIndex) => <div key={`${item.assetId}-${mediaIndex}`}><img src={item.secureUrl} alt={item.altText || ''} className="h-20 w-28 object-cover" /><Button aria-label="Remove room image" onClick={() => roomChange(index, 'media', room.media.filter((_, i) => i !== mediaIndex))}><Trash2 size={14} /></Button></div>)}</div><Button disabled={(room.media || []).length >= 8} onClick={() => setMediaTarget({ type: 'room', index })} className="mt-2"><ImagePlus size={15} />Add room image</Button></section>)}
      {section === 'Media' && <div className="space-y-6"><section><h2 className="font-semibold text-slate-900">Hero image</h2>{hotel.media?.hero?.secureUrl && <img src={hotel.media.hero.secureUrl} alt={hotel.media.hero.altText || ''} className="mt-2 aspect-video max-h-72 w-full max-w-lg object-cover" />}<Button onClick={() => setMediaTarget('hero')} className="mt-2"><ImagePlus size={15} />Choose from Media Library</Button></section><section><h2 className="font-semibold text-slate-900">Gallery ({hotel.media?.gallery?.length || 0}/12)</h2><div className="mt-2 grid grid-cols-2 gap-3 md:grid-cols-4">{hotel.media?.gallery?.map((item, index) => <div key={`${item.assetId}-${index}`}><img src={item.secureUrl} alt={item.altText || ''} className="aspect-video w-full object-cover" /><Button onClick={() => nested('media', 'gallery', hotel.media.gallery.filter((_, i) => i !== index))} aria-label="Remove gallery image"><Trash2 size={15} /></Button></div>)}</div><Button disabled={(hotel.media?.gallery?.length || 0) >= 12} onClick={() => setMediaTarget('gallery')} className="mt-2"><Plus size={15} />Add gallery image</Button></section></div>}
      {section === 'Contact & Vendor' && <div className="grid gap-4 md:grid-cols-2">{['reservationsPerson', 'phone', 'whatsapp', 'email', 'website'].map((key) => <Field key={key} label={key.replace(/([A-Z])/g, ' $1')} type={key === 'email' ? 'email' : 'text'} value={hotel.contact?.[key]} onChange={(value) => nested('contact', key, value)} />)}<label className="text-sm font-medium text-slate-700">Linked Operations Vendor (optional)<select value={hotel.vendorId || ''} onChange={(event) => change('vendorId', event.target.value || null)} className={inputStyle}><option value="">No linked vendor</option>{vendors.map((vendor) => <option key={vendor._id} value={vendor._id}>{vendor.name}</option>)}</select></label><div className="md:col-span-2"><Area label="Internal notes" value={hotel.internalNotes} onChange={(value) => change('internalNotes', value)} /></div></div>}
      {section === 'Commercial' && <div className="space-y-4"><p className="text-sm text-slate-600">Internal reference only. Rates never become quotation prices automatically.</p><Button onClick={() => change('ratePlans', [...hotel.ratePlans, { roomTypeId: '', mealPlan: 'EP', currency: 'INR', supplierRatePerNight: 0, customerReferenceRatePerNight: 0, taxPercent: 0, minNights: 1, active: true }])}><Plus size={15} />Add rate plan</Button>{hotel.ratePlans.map((rate, index) => <div key={rate.ratePlanId || index} className="grid gap-3 border-t border-slate-200 pt-4 md:grid-cols-3"><label className="text-sm font-medium text-slate-700">Room type<select value={rate.roomTypeId} onChange={(event) => rateChange(index, 'roomTypeId', event.target.value)} className={inputStyle}><option value="">Select saved room</option>{hotel.roomTypes.filter((room) => room.roomTypeId).map((room) => <option key={room.roomTypeId} value={room.roomTypeId}>{room.name}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Meal plan<select value={rate.mealPlan} onChange={(event) => rateChange(index, 'mealPlan', event.target.value)} className={inputStyle}>{hotel.availableMealPlans.map((plan) => <option key={plan}>{plan}</option>)}</select></label><Field label="Currency" value={rate.currency} onChange={(value) => rateChange(index, 'currency', value)} /><Field label="Supplier / night" type="number" min="0" value={rate.supplierRatePerNight} onChange={(value) => rateChange(index, 'supplierRatePerNight', value)} /><Field label="Customer reference / night" type="number" min="0" value={rate.customerReferenceRatePerNight} onChange={(value) => rateChange(index, 'customerReferenceRatePerNight', value)} /><Field label="Tax %" type="number" min="0" value={rate.taxPercent} onChange={(value) => rateChange(index, 'taxPercent', value)} /><Field label="Valid from" type="date" value={rate.validFrom?.slice?.(0, 10)} onChange={(value) => rateChange(index, 'validFrom', value || null)} /><Field label="Valid to" type="date" value={rate.validTo?.slice?.(0, 10)} onChange={(value) => rateChange(index, 'validTo', value || null)} /><Field label="Minimum nights" type="number" min="1" value={rate.minNights} onChange={(value) => rateChange(index, 'minNights', value)} /><Area label="Notes" value={rate.notes} onChange={(value) => rateChange(index, 'notes', value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rate.active !== false} onChange={(event) => rateChange(index, 'active', event.target.checked)} />Active</label><Button onClick={() => change('ratePlans', hotel.ratePlans.filter((_, i) => i !== index))}><Trash2 size={15} />Remove</Button></div>)}</div>}
      {section === 'Review' && <div className="space-y-4 text-sm"><p><strong>Property:</strong> {hotel.name || 'Unnamed'} · {hotel.location?.city || 'City missing'} · {hotel.propertyType}</p><p><strong>Rooms:</strong> {hotel.roomTypes.length} · <strong>Meal plans:</strong> {hotel.availableMealPlans.join(', ') || 'None'}</p><p><strong>Media:</strong> {hotel.media?.hero ? 'Hero selected' : 'Hero missing'} · {hotel.media?.gallery?.length || 0} gallery images</p>{activationIssues.length ? <p className="text-amber-800">To activate, add: {activationIssues.join(', ')}.</p> : <p className="text-emerald-800">Ready for activation after saving.</p>}{id && !readOnly && hotel.status !== 'ARCHIVED' && <div className="flex flex-wrap gap-2"><Button disabled={Boolean(activationIssues.length) || saving || hotel.status === 'ACTIVE'} onClick={() => status('ACTIVE')}>Activate</Button><Button disabled={saving || hotel.status === 'INACTIVE'} onClick={() => status('INACTIVE')}>Deactivate</Button><Button disabled={saving} onClick={() => status('ARCHIVED')}>Archive</Button></div>}</div>}
    </fieldset>
    <MediaLibraryModal isOpen={Boolean(mediaTarget)} purpose="hotel" initialDestination={hotel.location?.city || ''} onClose={() => setMediaTarget(null)} onOpenUpload={() => setUploadOpen(true)} keepOpenOnUpload onSelectMedia={chooseMedia} />
    <UploadLocationImageModal isOpen={uploadOpen} purpose="hotel" initialDestination={hotel.location?.city || ''} initialLocationName={hotel.name || ''} onClose={() => setUploadOpen(false)} onAssetCreated={(asset) => chooseMedia({ assetId: asset._id, url: asset.storage?.secureUrl, altText: asset.altText, caption: asset.caption })} />
  </div>;
}
