import React from 'react';
import QuotationPdfPage from '../components/QuotationPdfPage.jsx';
import PdfImage from '../components/PdfImage.jsx';
import { ApprovalBlock, BulletList, Facts, ItineraryDay, Money, PolicyEntries, RouteFlow } from '../components/templateShared.jsx';
import { chunkByWeight, chunkItinerary, chunkPolicyEntries } from '../pagination.js';
import { formatQuotationV2Date } from '../quotationV2.js';

export default function ExpeditionDossierTemplate({ model }) {
  const itineraryChunks = chunkItinerary(model.itinerary, 'minimal');
  const logisticsChunks = chunkByWeight([
    ...model.hotels.map((item) => ({ kind: 'hotel', item })),
    ...model.transport.map((item) => ({ kind: 'transport', item }))
  ], 7, () => 1);
  const policyChunks = chunkPolicyEntries([['inclusions', model.inclusions], ['exclusions', model.exclusions], ...Object.entries(model.policies)]
    .filter(([, value]) => Array.isArray(value) ? value.length : value));
  const pages = [];
  pages.push({ title: 'Overview Dossier', cover: true, className: 'dossier-cover', content: <><div className="dossier-banner"><div style={{ display: 'flex', justifyContent: 'space-between' }}><span>ISSUE DATE · {formatQuotationV2Date(model.meta.issuedAt)}</span><span>QUOTATION REF · {model.meta.quotationNumber}</span><span>VALID TILL · {formatQuotationV2Date(model.meta.validUntil)}</span></div><h2 style={{ margin: '22px 0 0', font: '600 20px Georgia,serif', letterSpacing: '.18em' }}>WANDERLUXE</h2></div><div className="dossier-cover-body"><span className="dossier-stamp">EXPEDITION DOSSIER · V{model.meta.version}</span><h1 className="pdf-title">{model.journey.title}</h1><p style={{ font: 'italic 18px Georgia,serif', color: '#8b1e1e' }}>{model.journey.destination}</p><div style={{ marginTop: 20 }}><RouteFlow stops={model.journey.routeStops} compact /></div><div className="dossier-grid" style={{ marginTop: 28 }}><div><Facts items={[["Client", model.customer.name], ["Contact", model.customer.email || model.customer.phone], ["Duration", model.journey.duration], ["Travelers", model.journey.travelers.total], ["Travel style", model.journey.travelStyle], ["Stay category", model.hotels.find((item) => item.selected)?.category || model.hotels[0]?.category], ["Transport", [...new Set(model.transport.map((item) => item.mode))].join(', ')], ["Nights", model.journey.nights]]} /><div style={{ marginTop: 22 }}><p className="pdf-kicker">EXPERIENCE BLUEPRINT</p><p className="pdf-copy">{model.journey.personalNote || model.journey.specialRequests}</p><BulletList items={model.journey.highlights.slice(0, 4)} /></div></div><div><div className="dossier-tape" /><div className="dossier-photo"><PdfImage src={model.journey.coverImage} alt={model.journey.destination} /><p className="journey-note">{model.journey.destination || 'Journey reference'}</p></div>{model.advisor && <div className="pdf-policy"><h3>Journey specialist</h3><p>{model.advisor.name || 'WanderLuxe Travel Desk'}<br />{model.advisor.email || model.advisor.phone}</p></div>}</div></div></div></> });
  itineraryChunks.forEach((days, index) => pages.push({ title: `Day-Wise Journey Circuit${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">FIELD PLAN {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Day-Wise Journey Circuit{index ? ' · Continued' : ''}</h2><div className="pdf-itinerary-list">{days.map((day) => <ItineraryDay key={day.day} day={day} compact image={false} />)}</div></> }));
  logisticsChunks.forEach((entries, index) => pages.push({ title: `Accommodation & Transfer Matrix${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">LOGISTICS MATRIX {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Accommodation & Transfer Matrix</h2><table className="pdf-payment-table"><thead><tr><th>Type</th><th>Stay / route</th><th>Room / mode</th><th>Duration</th></tr></thead><tbody>{entries.map(({ kind, item }) => kind === 'hotel' ? <tr key={`h-${item.id}`}><td>{item.selected ? 'Recommended stay' : 'Stay option'}</td><td>{item.hotelName} · {item.city}</td><td>{[item.roomType, item.mealPlan].filter(Boolean).join(' · ')}</td><td>{item.nights ? `${item.nights} nights` : 'TBC'}</td></tr> : <tr key={`t-${item.id}`}><td>Transport</td><td>{[item.pickup, item.drop].filter(Boolean).join(' → ')}</td><td>{item.title}</td><td>{item.schedule.departureDate ? formatQuotationV2Date(item.schedule.departureDate) : 'TBC'}</td></tr>)}</tbody></table></> }));
  pages.push({ title: 'Investment Summary', content: <><span className="dossier-stamp">COMMERCIAL SUMMARY</span><h2 className="pdf-section-title">Investment Summary</h2><div className="pdf-price-hero" style={{ marginTop: 20, background: '#6b4a2d' }}><span className="pdf-kicker">TOTAL PACKAGE VALUE</span><strong><Money value={model.pricing.finalCustomerPrice} currency={model.pricing.currency} /></strong></div><div style={{ marginTop: 18 }}><Facts items={[["Reservation / deposit", <Money key="deposit" value={model.pricing.depositAmount} currency={model.pricing.currency} />], ["Balance", <Money key="balance" value={model.pricing.balanceAmount} currency={model.pricing.currency} />], ["Valid until", formatQuotationV2Date(model.meta.validUntil)], ["Travelers", model.journey.travelers.total]]} /></div>{model.pricing.paymentSchedule.length > 0 && <table className="pdf-payment-table"><thead><tr><th>Payment milestone</th><th>Amount</th><th>Due date</th></tr></thead><tbody>{model.pricing.paymentSchedule.map((item, index) => <tr key={`${item.label}-${index}`}><td>{item.label}</td><td><Money value={item.amount} currency={model.pricing.currency} /></td><td>{formatQuotationV2Date(item.dueDate)}</td></tr>)}</tbody></table>}<div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 18 }}><ApprovalBlock model={model} /><div className="pdf-approval"><span>WANDERLUXE CONTACT</span><strong>{model.advisor?.name || 'WanderLuxe Travel Desk'}</strong><small>{model.advisor?.email || model.advisor?.phone || model.meta.quotationNumber}</small></div></div></> });
  policyChunks.forEach((entries, index) => pages.push({ title: `Terms Summary${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">TERMS FILE {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Terms Summary</h2><PolicyEntries entries={entries} /></> }));
  const pageCount = pages.length;
  return <div className="quotation-pdf-stack">{pages.map((page, index) => <QuotationPdfPage key={`${page.title}-${index}`} model={model} templateKey="minimal" pageNumber={index + 1} pageCount={pageCount} title={page.title} cover={page.cover} className={page.className}>{page.content}</QuotationPdfPage>)}</div>;
}
