import React from 'react';
import QuotationPdfPage from '../components/QuotationPdfPage.jsx';
import PdfImage from '../components/PdfImage.jsx';
import { ApprovalBlock, BulletList, Experiences, Facts, HotelCard, ItineraryDay, Money, PolicyEntries, RouteFlow, TransportCard } from '../components/templateShared.jsx';
import TravelDocumentCard from '../components/TravelDocumentCard.jsx';
import { chunkByWeight, chunkItinerary, chunkPolicyEntries, splitHotel } from '../pagination.js';
import { formatQuotationV2Date } from '../quotationV2.js';

export default function ExpeditionDossierTemplate({ model }) {
  const itineraryChunks = chunkItinerary(model.itinerary, 'minimal');
  const logisticsChunks = chunkByWeight([
    ...model.hotels.map((item) => ({ kind: 'hotel', item })),
    ...model.transport.map((item) => ({ kind: 'transport', item }))
  ], 7, () => 1);
  const policyChunks = chunkPolicyEntries([['inclusions', model.inclusions], ['exclusions', model.exclusions], ...Object.entries(model.policies)]
    .filter(([, value]) => Array.isArray(value) ? value.length : value), 1400);
  const pages = [];
  pages.push({ title: 'Overview Dossier', cover: true, className: 'dossier-cover', content: <><div className="dossier-banner"><div style={{ display: 'flex', justifyContent: 'space-between' }}><span>ISSUE DATE · {formatQuotationV2Date(model.meta.issuedAt)}</span><span>QUOTATION REF · {model.meta.quotationNumber}</span><span>VALID TILL · {formatQuotationV2Date(model.meta.validUntil)}</span></div><h2 style={{ margin: '22px 0 0', font: '600 20px Georgia,serif', letterSpacing: '.18em' }}>WANDERLUXE</h2></div><div className="dossier-cover-body"><span className="dossier-stamp">EXPEDITION DOSSIER · V{model.meta.version}</span><h1 className="pdf-title">{model.journey.title}</h1><p style={{ font: 'italic 18px Georgia,serif', color: '#8b1e1e' }}>{model.journey.destination}</p><div style={{ marginTop: 20 }}><RouteFlow stops={model.journey.routeStops} compact /></div><div className="dossier-grid" style={{ marginTop: 28 }}><div><Facts items={[["Client", model.customer.name], ["Origin", model.journey.origin], ["Dates", model.journey.dateLabel || `${formatQuotationV2Date(model.journey.startDate)} - ${formatQuotationV2Date(model.journey.endDate)}`], ["Duration", model.journey.duration], ["Travelers", model.journey.travelers.label || model.journey.travelers.total], ["Travel style", model.journey.travelStyle], ["Preferences", model.preferences ? [...model.preferences.interests, model.preferences.stayPreference, model.preferences.dietaryPreference].filter(Boolean).join(' · ') : ''], ["Nights", model.journey.nights]]} /><div style={{ marginTop: 22 }}><p className="pdf-kicker">EXPERIENCE BLUEPRINT</p><p className="pdf-copy">{model.journey.personalNote || model.journey.specialRequests}</p><BulletList items={model.journey.highlights.slice(0, 4)} /></div></div><div><div className="dossier-tape" /><div className="dossier-photo"><PdfImage src={model.journey.coverImage} alt={model.journey.destination} /><p className="journey-note">{model.journey.destination || 'Journey reference'}</p></div>{model.advisor && <div className="pdf-policy"><h3>Journey specialist</h3><p>{model.advisor.name || 'WanderLuxe Travel Desk'}<br />{model.advisor.email || model.advisor.phone}</p></div>}</div></div></div></> });
  itineraryChunks.forEach((days, index) => pages.push({ title: `Day-Wise Journey Circuit${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">FIELD PLAN {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Day-Wise Journey Circuit{index ? ' · Continued' : ''}</h2><div className="pdf-itinerary-list">{days.map((day) => <ItineraryDay key={day.fragmentId || day.day} day={day} compact image={false} />)}</div></> }));
  logisticsChunks.forEach((entries, index) => pages.push({ title: `Accommodation & Transfer Matrix${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">LOGISTICS MATRIX {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Accommodation & Transfer Matrix</h2><table className="pdf-payment-table"><thead><tr><th>Type</th><th>Stay / route</th><th>Room / mode</th><th>Duration</th></tr></thead><tbody>{entries.map(({ kind, item }) => kind === 'hotel' ? <tr key={`h-${item.id}`}><td>{item.selected ? 'Recommended stay' : 'Stay option'}</td><td>{item.hotelName} · {item.city}</td><td>{[item.roomType, item.mealPlan].filter(Boolean).join(' · ')}</td><td>{item.nights ? `${item.nights} nights` : 'TBC'}</td></tr> : <tr key={`t-${item.id}`}><td>Transport</td><td>{[item.pickup, item.drop].filter(Boolean).join(' → ')}</td><td>{item.title}</td><td>{item.schedule.departureDate ? formatQuotationV2Date(item.schedule.departureDate) : 'TBC'}</td></tr>)}</tbody></table></> }));
  model.hotels.filter((item) => item.heroImage || item.gallery.length || item.notes || item.amenities.length).flatMap((hotel) => splitHotel(hotel, 1)).forEach((hotel, index) => pages.push({ title: `Stay Detail · ${index + 1}`, content: <><span className="dossier-stamp">STAY DETAIL</span><h2 className="pdf-section-title">{hotel.hotelName}</h2><div className="pdf-card-grid"><HotelCard hotel={hotel} galleryLimit={1} /></div></> }));
  chunkByWeight(model.transport.filter((item) => item.media.length || item.notes || item.reference || item.cabinClass || item.seatDetails || item.baggage), 2, () => 1)
    .forEach((items, index) => pages.push({ title: `Transport Detail · ${index + 1}`, content: <><span className="dossier-stamp">TRANSPORT DETAIL</span><h2 className="pdf-section-title">Transport Detail</h2><div className="pdf-card-grid">{items.map((item) => <TransportCard key={item.id} item={item} />)}</div></> }));
  if (model.activities.length || model.addOns.length) chunkByWeight([...model.activities.map((item) => ({ ...item, kind: 'activity' })), ...model.addOns.map((item) => ({ ...item, kind: 'addon' }))], 8, (item) => 1 + (item.description?.length || 0) / 350).forEach((items, index) => pages.push({ title: `Selected Services${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">SERVICE FILE</span><h2 className="pdf-section-title">Selected Services</h2><Experiences activities={items.filter((item) => item.kind === 'activity')} addOns={items.filter((item) => item.kind === 'addon')} /></> }));
  chunkByWeight(model.allCustomerDocuments, 7, () => 1).forEach((documents, index) => pages.push({ title: `Travel Document Register${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">DOCUMENT REGISTER</span><h2 className="pdf-section-title">Travel Documents</h2><table className="pdf-payment-table"><thead><tr><th>Type</th><th>Related service</th><th>Reference</th><th>Document</th></tr></thead><tbody>{documents.map((item) => <tr key={item.id || item.secureUrl}><td>{item.documentType}</td><td>{item.relation?.name || 'General'}</td><td>{item.bookingReference || '—'}</td><td>{item.title}</td></tr>)}</tbody></table></> }));
  model.allCustomerDocuments.forEach((document, index) => pages.push({ title: `Travel Documents · ${index + 1}`, content: <><span className="dossier-stamp">DOCUMENT {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Ticket / Voucher</h2><TravelDocumentCard document={document} /></> }));
  pages.push({ title: 'Investment Summary', content: <><span className="dossier-stamp">COMMERCIAL SUMMARY</span><h2 className="pdf-section-title">Investment Summary</h2><div className="pdf-price-hero" style={{ marginTop: 20, background: '#6b4a2d' }}><span className="pdf-kicker">TOTAL PACKAGE VALUE</span><strong><Money value={model.pricing.finalCustomerPrice} currency={model.pricing.currency} /></strong></div><div style={{ marginTop: 18 }}><Facts items={[["Reservation / deposit", <Money key="deposit" value={model.pricing.depositAmount} currency={model.pricing.currency} />], ["Balance", <Money key="balance" value={model.pricing.balanceAmount} currency={model.pricing.currency} />], ["Valid until", formatQuotationV2Date(model.meta.validUntil)], ["Travelers", model.journey.travelers.total]]} /></div>{model.pricing.paymentSchedule.length > 0 && <table className="pdf-payment-table"><thead><tr><th>Payment milestone</th><th>Amount</th><th>Due date</th></tr></thead><tbody>{model.pricing.paymentSchedule.map((item, index) => <tr key={`${item.label}-${index}`}><td>{item.label}</td><td><Money value={item.amount} currency={model.pricing.currency} /></td><td>{formatQuotationV2Date(item.dueDate)}</td></tr>)}</tbody></table>}<div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 18 }}><ApprovalBlock model={model} /><div className="pdf-approval"><span>WANDERLUXE CONTACT</span><strong>{model.advisor?.name || 'WanderLuxe Travel Desk'}</strong><small>{model.advisor?.email || model.advisor?.phone || model.meta.quotationNumber}</small></div></div></> });
  policyChunks.forEach((entries, index) => pages.push({ title: `Terms Summary${index ? ' · Continued' : ''}`, content: <><span className="dossier-stamp">TERMS FILE {String(index + 1).padStart(2, '0')}</span><h2 className="pdf-section-title">Terms Summary</h2><PolicyEntries entries={entries} /></> }));
  const pageCount = pages.length;
  return <div className="quotation-pdf-stack">{pages.map((page, index) => <QuotationPdfPage key={`${page.title}-${index}`} model={model} templateKey="minimal" pageNumber={index + 1} pageCount={pageCount} title={page.title} cover={page.cover} className={page.className}>{page.content}</QuotationPdfPage>)}</div>;
}
