import React from 'react';
import QuotationPdfPage from '../components/QuotationPdfPage.jsx';
import PdfImage from '../components/PdfImage.jsx';
import { ApprovalBlock, BulletList, Facts, HotelCard, ItineraryDay, Money, PolicyEntries, RouteFlow, TransportCard } from '../components/templateShared.jsx';
import { chunkByWeight, chunkItinerary, chunkPolicyEntries } from '../pagination.js';
import { formatQuotationV2Date } from '../quotationV2.js';

export default function JourneyJournalTemplate({ model }) {
  const itineraryChunks = chunkItinerary(model.itinerary, 'journey');
  const logisticsChunks = chunkByWeight([
    ...model.hotels.map((item) => ({ kind: 'hotel', item })),
    ...model.transport.map((item) => ({ kind: 'transport', item }))
  ], 5.5, ({ kind, item }) => kind === 'hotel' ? 1.8 + (item.imageUrl ? .4 : 0) : 1.2);
  const policyChunks = chunkPolicyEntries([['inclusions', model.inclusions], ['exclusions', model.exclusions], ...Object.entries(model.policies)]
    .filter(([, value]) => Array.isArray(value) ? value.length : value), 1800);
  const pages = [];
  pages.push({ title: 'Travel Journal', cover: true, className: 'journey-cover', content: <div className="journey-cover-inner"><div className="journey-stamp">PRIVATE TRAVEL JOURNAL</div><p className="pdf-kicker" style={{ marginTop: 26 }}>{model.meta.quotationNumber} · VERSION {model.meta.version}</p><h1 className="pdf-title">{model.journey.title}</h1><p style={{ marginTop: 18, fontSize: 18, color: '#c86d51' }}>{model.journey.destination}</p><div style={{ maxWidth: 390, marginTop: 28 }}><RouteFlow stops={model.journey.routeStops} compact /></div><div className="journey-polaroids">{[model.journey.coverImage, model.journey.secondaryImages[0]].filter(Boolean).map((src, index) => <div className="journey-polaroid" key={src}><PdfImage src={src} alt={index ? 'Selected stay' : model.journey.destination} /></div>)}</div><div style={{ position: 'absolute', left: 54, bottom: 58, width: 360 }}><Facts items={[["Lead traveler", model.customer.name], ["Dates", `${formatQuotationV2Date(model.journey.startDate)} - ${formatQuotationV2Date(model.journey.endDate)}`], ["Travelers", model.journey.travelers.total], ["Duration", model.journey.duration], ["Travel style", model.journey.travelStyle], ["Advisor", model.advisor?.name || 'WanderLuxe Travel Desk']]} /></div></div> });
  pages.push({ title: 'Trip Snapshot & Highlights', content: <><p className="journey-note">The journey blueprint</p><h2 className="pdf-section-title">Trip Snapshot & Highlights</h2><div style={{ marginTop: 22 }}><Facts items={[["Destination", model.journey.destination], ["Duration", model.journey.duration], ["Travelers", `${model.journey.travelers.total} guests`], ["Dates", `${formatQuotationV2Date(model.journey.startDate)} - ${formatQuotationV2Date(model.journey.endDate)}`], ["Night stays", model.journey.nights], ["Stay category", model.hotels.find((item) => item.selected)?.category || model.hotels[0]?.category], ["Transport", [...new Set(model.transport.map((item) => item.mode))].join(', ')], ["Travel style", model.journey.travelStyle]]} /></div><div style={{ marginTop: 30 }}><p className="pdf-kicker">SIGNATURE JOURNEY HIGHLIGHTS</p><div className="pdf-card-grid">{model.journey.highlights.slice(0, 6).map((item, index) => <div className="journey-paper-card" key={item}><span className="journey-stamp">{String(index + 1).padStart(2, '0')}</span><p className="pdf-copy" style={{ marginTop: 12 }}>{item}</p></div>)}</div></div>{model.journey.secondaryImages[1] && <PdfImage src={model.journey.secondaryImages[1]} alt={model.journey.destination} className="signature-feature-image" />}</> });
  itineraryChunks.forEach((days, index) => pages.push({ title: `Day-by-Day Journey${index ? ' · Continued' : ''}`, content: <><p className="journey-note">notes from the road</p><h2 className="pdf-section-title">Day-by-Day Journey{index ? ' · Continued' : ''}</h2><div className="pdf-itinerary-list">{days.map((day) => <ItineraryDay key={day.day} day={day} image={model.settings.showItineraryGallery} />)}</div></> }));
  logisticsChunks.forEach((entries, index) => pages.push({ title: `Accommodations & Transport${index ? ' · Continued' : ''}`, content: <><p className="pdf-kicker">STAYS & MOVEMENT</p><h2 className="pdf-section-title">Accommodations & Transport</h2><div className="pdf-card-grid">{entries.map(({ kind, item }) => kind === 'hotel' ? <HotelCard key={`h-${item.id}`} hotel={item} /> : <TransportCard key={`t-${item.id}`} item={item} />)}</div>{model.attachments.length > 0 && <div className="journey-paper-card" style={{ marginTop: 20 }}><p className="pdf-kicker">VISIBLE TRAVEL DOCUMENTS</p><BulletList items={model.attachments.map((item) => item.title)} /></div>}</> }));
  pages.push({ title: 'Journey Investment', className: 'journey-ledger', content: <><p className="journey-note">the commercial page</p><h2 className="pdf-section-title">Journey Investment</h2><div className="pdf-price-hero" style={{ marginTop: 24, background: '#3b5e4b' }}><span className="pdf-kicker">FINAL CUSTOMER PRICE</span><strong><Money value={model.pricing.finalCustomerPrice} currency={model.pricing.currency} /></strong></div><div style={{ marginTop: 20 }}><Facts items={[["Deposit", <Money key="deposit" value={model.pricing.depositAmount} currency={model.pricing.currency} />], ["Balance", <Money key="balance" value={model.pricing.balanceAmount} currency={model.pricing.currency} />], ["Valid until", formatQuotationV2Date(model.meta.validUntil)], ["Travelers", model.journey.travelers.total]]} /></div>{model.pricing.customerVisibleComponents.length > 0 && <div style={{ marginTop: 20 }}><p className="pdf-kicker">CUSTOMER-FACING BREAKDOWN</p><Facts items={model.pricing.customerVisibleComponents.map(([label, amount]) => [label, <Money key={label} value={amount} currency={model.pricing.currency} />])} /></div>}{model.pricing.paymentSchedule.length > 0 && <table className="pdf-payment-table"><thead><tr><th>Milestone</th><th>Amount</th><th>Due date</th><th>Notes</th></tr></thead><tbody>{model.pricing.paymentSchedule.map((item, index) => <tr key={`${item.label}-${index}`}><td>{item.label}</td><td><Money value={item.amount} currency={model.pricing.currency} /></td><td>{formatQuotationV2Date(item.dueDate)}</td><td>{item.notes}</td></tr>)}</tbody></table>}{model.pricing.priceNotes && <p className="pdf-copy">{model.pricing.priceNotes}</p>}</> });
  policyChunks.forEach((entries, index) => pages.push({ title: `Terms & Concierge${index ? ' · Continued' : ''}`, content: <><p className="journey-note">before you travel</p><h2 className="pdf-section-title">{index ? 'Travel Notes Continued' : 'Terms & Concierge'}</h2><PolicyEntries entries={entries} cardClass="journey-paper-card pdf-policy" />{index === policyChunks.length - 1 && <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginTop: 22 }}>{model.advisor && <div className="journey-paper-card"><p className="pdf-kicker">YOUR ADVISOR</p><strong>{model.advisor.name || 'WanderLuxe Travel Desk'}</strong><p className="pdf-copy">{[model.advisor.email, model.advisor.phone].filter(Boolean).join(' · ')}</p></div>}<ApprovalBlock model={model} /></div>}</> }));
  const pageCount = pages.length;
  return <div className="quotation-pdf-stack">{pages.map((page, index) => <QuotationPdfPage key={`${page.title}-${index}`} model={model} templateKey="journey" pageNumber={index + 1} pageCount={pageCount} title={page.title} cover={page.cover} className={page.className}>{page.content}</QuotationPdfPage>)}</div>;
}
