import React from 'react';
import QuotationPdfPage from '../components/QuotationPdfPage.jsx';
import PdfImage from '../components/PdfImage.jsx';
import { ApprovalBlock, BulletList, Facts, HotelCard, ItineraryDay, Money, PolicyEntries, RouteFlow, TransportCard } from '../components/templateShared.jsx';
import { chunkHotels, chunkItinerary, chunkPolicyEntries, chunkTransport } from '../pagination.js';
import { formatQuotationV2Date } from '../quotationV2.js';

export default function SignatureLuxeTemplate({ model }) {
  const itineraryChunks = chunkItinerary(model.itinerary, 'signature_luxe');
  const hotelChunks = chunkHotels(model.hotels, 'signature_luxe');
  const transportChunks = chunkTransport(model.transport, 'signature_luxe');
  const policyEntries = [['inclusions', model.inclusions], ['exclusions', model.exclusions], ...Object.entries(model.policies)]
    .filter(([, value]) => Array.isArray(value) ? value.length : value);
  const policyChunks = chunkPolicyEntries(policyEntries);
  const pages = [];

  pages.push({ title: 'Cover', cover: true, className: 'signature-cover', content: <>
    {model.journey.coverImage && <PdfImage src={model.journey.coverImage} alt="" className="signature-cover-image" />}
    <div className="signature-cover-inner"><div className="signature-brand">WANDERLUXE</div><div className="signature-cover-main"><p className="pdf-kicker" style={{ color: '#d4af37' }}>PRIVATE JOURNEY PROPOSAL · {model.meta.quotationNumber} · V{model.meta.version}</p><h1 className="pdf-title">{model.journey.title}</h1><p className="signature-cover-sub">{model.journey.destination}{model.journey.travelStyle ? ` · ${model.journey.travelStyle}` : ''}</p><div style={{ marginTop: 24 }}><RouteFlow stops={model.journey.routeStops} /></div></div><div className="signature-cover-meta"><div><span>CURATED FOR</span><strong>{model.customer.name}</strong></div><div><span>DATES</span><strong>{formatQuotationV2Date(model.journey.startDate)} - {formatQuotationV2Date(model.journey.endDate)}</strong></div><div><span>TRAVELERS</span><strong>{model.journey.travelers.total} guests</strong></div><div><span>ADVISOR</span><strong>{model.advisor?.name || 'WanderLuxe Travel Desk'}</strong></div></div></div>
  </> });

  pages.push({ title: 'A Personal Invitation', content: <><p className="pdf-kicker">A PERSONAL INVITATION</p><h2 className="pdf-section-title">Welcome to {model.journey.destination || 'your next remarkable journey'}</h2><div className="signature-split"><div>{model.journey.personalNote ? <p className="pdf-copy" style={{ fontSize: 14, lineHeight: 1.9 }}>{model.journey.personalNote}</p> : <p className="pdf-copy" style={{ fontSize: 14, lineHeight: 1.9 }}>A privately prepared proposal for {model.customer.name}, shaped around the journey details selected with WanderLuxe.</p>}{model.journey.secondaryImages[0] && <PdfImage src={model.journey.secondaryImages[0]} alt={model.journey.destination} className="signature-feature-image" />}</div><div><p className="pdf-kicker">CURATED JOURNEY HIGHLIGHTS</p><div className="signature-highlight-grid" style={{ marginTop: 14 }}>{model.journey.highlights.slice(0, 4).map((item, index) => <div className="signature-highlight" key={item}><strong>{String(index + 1).padStart(2, '0')}</strong><span>{item}</span></div>)}</div>{model.journey.specialRequests && <div style={{ marginTop: 18 }}><p className="pdf-kicker">TRAVEL NOTES</p><p className="pdf-copy">{model.journey.specialRequests}</p></div>}</div></div></> });

  pages.push({ title: 'Journey at a Glance', content: <><p className="pdf-kicker">EXECUTIVE OVERVIEW</p><h2 className="pdf-section-title">Journey at a Glance</h2><div style={{ marginTop: 24 }}><Facts items={[
    ['Final journey investment', <Money key="overview-final" value={model.pricing.finalCustomerPrice} currency={model.pricing.currency} />], ['Duration', model.journey.duration], ['Travelers', `${model.journey.travelers.total} guests`], ['Major stops', model.journey.routeStops.length],
    ['Hotels', model.hotels.length], ['Transport modes', [...new Set(model.transport.map((item) => item.mode))].join(', ')], ['Activities', model.activities.length], ['Travel style', model.journey.travelStyle]
  ]} /></div><div style={{ marginTop: 36 }}><p className="pdf-kicker">JOURNEY ROUTE</p><div style={{ marginTop: 14 }}><RouteFlow stops={model.journey.routeStops} /></div></div>{model.journey.coverImage && <PdfImage src={model.journey.coverImage} alt={model.journey.destination} className="signature-feature-image" />}</> });

  itineraryChunks.forEach((days) => pages.push({ title: `Itinerary Chronicle · Days ${String(days[0].day).padStart(2, '0')}-${String(days.at(-1).day).padStart(2, '0')}`, content: <><p className="pdf-kicker">THE DAILY CHRONICLE</p><h2 className="pdf-section-title">Itinerary Chronicle</h2><div className="pdf-itinerary-list">{days.map((day) => <ItineraryDay key={day.day} day={day} detailed image={model.settings.showItineraryGallery} />)}</div></> }));

  hotelChunks.forEach((hotels, index) => pages.push({ title: `Handpicked Stays${index ? ' · Continued' : ''}`, content: <><p className="pdf-kicker">BESPOKE STAYS</p><h2 className="pdf-section-title">Handpicked Stays{index ? ' · Continued' : ''}</h2><div className="pdf-card-grid">{hotels.map((hotel) => <HotelCard key={hotel.id} hotel={hotel} detailed />)}</div></> }));
  transportChunks.forEach((items, index) => pages.push({ title: `Transport & Logistics${index ? ' · Continued' : ''}`, content: <><p className="pdf-kicker">SEAMLESS MOVEMENT</p><h2 className="pdf-section-title">Dedicated Transport & Logistics</h2><div className="pdf-card-grid">{items.map((item) => <TransportCard key={item.id} item={item} />)}</div>{model.attachments.length > 0 && <div style={{ marginTop: 28 }}><p className="pdf-kicker">CUSTOMER DOCUMENTS</p><BulletList items={model.attachments.map((item) => item.title)} /></div>}</> }));

  pages.push({ title: 'Your Journey Investment', content: <><p className="pdf-kicker">FINANCIAL SUMMARY & PAYMENT PLAN</p><h2 className="pdf-section-title">Your Journey Investment</h2><div className="pdf-price-hero" style={{ marginTop: 24 }}><span className="pdf-kicker">FINAL CUSTOMER PRICE</span><strong><Money value={model.pricing.finalCustomerPrice} currency={model.pricing.currency} /></strong><p className="pdf-copy">The final customer price entered for this proposal.</p></div><div style={{ marginTop: 20 }}><Facts items={[["Deposit", <Money key="deposit" value={model.pricing.depositAmount} currency={model.pricing.currency} />], ["Balance", <Money key="balance" value={model.pricing.balanceAmount} currency={model.pricing.currency} />], ["Valid until", formatQuotationV2Date(model.meta.validUntil)], ["Travelers", model.journey.travelers.total]]} /></div>{model.pricing.customerVisibleComponents.length > 0 && <div style={{ marginTop: 22 }}><p className="pdf-kicker">CUSTOMER-FACING COMPONENTS</p><Facts items={model.pricing.customerVisibleComponents.map(([label, amount]) => [label, <Money key={label} value={amount} currency={model.pricing.currency} />])} /></div>}{model.pricing.paymentSchedule.length > 0 && <table className="pdf-payment-table"><thead><tr><th>Milestone</th><th>Amount</th><th>Due date</th><th>Notes</th></tr></thead><tbody>{model.pricing.paymentSchedule.map((item, index) => <tr key={`${item.label}-${index}`}><td>{item.label}</td><td><Money value={item.amount} currency={model.pricing.currency} /></td><td>{formatQuotationV2Date(item.dueDate)}</td><td>{item.notes}</td></tr>)}</tbody></table>}{model.pricing.priceNotes && <p className="pdf-copy">{model.pricing.priceNotes}</p>}</> });

  policyChunks.forEach((entries, index) => pages.push({ title: `Terms of Journey${index ? ' · Continued' : ''}`, content: <><p className="pdf-kicker">TRAVEL CLARITY</p><h2 className="pdf-section-title">{index ? 'Important Information' : 'Terms of Journey'}</h2><PolicyEntries entries={entries} /></> }));

  pages.push({ title: 'Your Journey Starts Here', cover: true, className: 'signature-final', content: <><div><p className="signature-brand">WANDERLUXE</p><p className="pdf-kicker" style={{ marginTop: 90, color: '#d4af37' }}>PRIVATE JOURNEY PROPOSAL</p><h2 className="pdf-title" style={{ marginTop: 18 }}>Your Journey<br />Starts Here</h2><p className="signature-cover-sub">{model.journey.title} · {model.meta.quotationNumber} · Version {model.meta.version}</p></div><div><ApprovalBlock model={model} /><div className="signature-cover-meta" style={{ marginTop: 30 }}><div><span>TRAVELER</span><strong>{model.customer.name}</strong></div><div><span>VALID UNTIL</span><strong>{formatQuotationV2Date(model.meta.validUntil)}</strong></div>{model.advisor && <><div><span>ADVISOR</span><strong>{model.advisor.name || 'WanderLuxe'}</strong></div><div><span>CONTACT</span><strong>{model.advisor.email || model.advisor.phone || 'WanderLuxe Travel Desk'}</strong></div></>}</div></div></> });

  const pageCount = pages.length;
  return <div className="quotation-pdf-stack">{pages.map((page, index) => <QuotationPdfPage key={`${page.title}-${index}`} model={model} templateKey="signature_luxe" pageNumber={index + 1} pageCount={pageCount} title={page.title} cover={page.cover} className={page.className}>{page.content}</QuotationPdfPage>)}</div>;
}
