import React, { useEffect, useState } from 'react';
import { X } from 'lucide-react';
import { userRoleLabel } from '../userAdminHelpers.js';

const empty = { name: '', email: '', password: '', role: 'sales', isActive: true };

const CreateStaffModal = ({ open, actor, busy, error, onClose, onConfirm }) => {
  const [form, setForm] = useState(empty);
  useEffect(() => { if (open) setForm(empty); }, [open]);
  if (!open) return null;
  const roles = actor?.role === 'super_admin' ? ['admin', 'sales', 'marketing', 'super_admin'] : ['admin', 'sales', 'marketing'];
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/65 p-4" role="dialog" aria-modal="true"><form onSubmit={(event) => { event.preventDefault(); onConfirm(form); }} className="w-full max-w-lg rounded-xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-200 p-5"><div><h2 className="font-semibold text-slate-950">Create Staff account</h2><p className="mt-1 text-xs text-slate-500">Creates one MongoDB User using the existing password authentication flow.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={17} /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700 sm:col-span-2">Name<input required value={form.name} onChange={(event) => update('name', event.target.value)} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 outline-none focus:border-emerald-500" /></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">Email<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 outline-none focus:border-emerald-500" /></label><label className="text-sm font-medium text-slate-700">Temporary password<input required minLength="6" type="password" value={form.password} onChange={(event) => update('password', event.target.value)} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 outline-none focus:border-emerald-500" /></label><label className="text-sm font-medium text-slate-700">Role<select value={form.role} onChange={(event) => update('role', event.target.value)} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 outline-none focus:border-emerald-500">{roles.map((role) => <option key={role} value={role}>{userRoleLabel(role)}</option>)}</select></label><label className="flex items-center gap-2 text-sm text-slate-700 sm:col-span-2"><input type="checkbox" checked={form.isActive} onChange={(event) => update('isActive', event.target.checked)} />Account active immediately</label>{error && <p className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800 sm:col-span-2">{error}</p>}</div><footer className="flex justify-end gap-2 border-t border-slate-200 p-4"><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700">Cancel</button><button type="submit" disabled={busy} className="min-h-10 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Creating…' : 'Create Staff'}</button></footer></form></div>;
};

export default CreateStaffModal;

