import { useCallback, useEffect, useState } from 'react';
import { Building2, ChevronLeft, ChevronRight, MapPin, Plus, RefreshCw, Search, Truck, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getOperationsVendorsApi } from '../../../../services/api.js';
import OperationsMetricCard from '../components/OperationsMetricCard.jsx';
import OperationsStatusBadge from '../components/OperationsStatusBadge.jsx';
import { formatOperationsDate } from '../helpers/operationsFormatters.js';

const filtersInitial = { search: '', type: 'all', status: 'all', city: '', sort: 'recent' };
const selectClass = 'min-h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-emerald-500';

export default function VendorsWorkspace() {
  const [vendors, setVendors] = useState([]); const [filters, setFilters] = useState(filtersInitial); const [summary, setSummary] = useState({ active: 0, inactive: 0, hotels: 0, transport: 0, activitiesAndGuides: 0 }); const [pagination, setPagination] = useState({ page: 1, pages: 0, total: 0 }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await getOperationsVendorsApi({ ...filters, page, limit: 20 }); setVendors(response.data || []); setSummary(response.summary || {}); setPagination(response.pagination || {}); } catch (requestError) { setError(requestError.message || 'Unable to load Vendors.'); } finally { setLoading(false); } }, [filters, page]);
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 250); return () => clearTimeout(timer); }, [load]);
  const change = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  return <div className="space-y-5"><header className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Operations · Supply</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Vendor Directory</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Maintain approved fulfillment contacts and assign only active, compatible Vendors to Trip Execution.</p></div><div className="flex gap-2"><button onClick={load} disabled={loading} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/>Refresh</button><Link to="/staff/operations/vendors/new" className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white"><Plus size={16}/>New Vendor</Link></div></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><OperationsMetricCard label="Active" value={summary.active || 0} detail="Available to assign" icon={UsersRound} tone="emerald"/><OperationsMetricCard label="Inactive" value={summary.inactive || 0} detail="Retained history" icon={UsersRound} tone="slate"/><OperationsMetricCard label="Hotels" value={summary.hotels || 0} detail="Stay providers" icon={Building2} tone="sky"/><OperationsMetricCard label="Transport" value={summary.transport || 0} detail="Transport & drivers" icon={Truck} tone="amber"/><OperationsMetricCard label="Activities & guides" value={summary.activitiesAndGuides || 0} detail="Local fulfillment" icon={MapPin} tone="slate"/></div>
    <section className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-2"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input value={filters.search} onChange={(event) => change('search',event.target.value)} placeholder="Name, code, contact, city…" className="min-h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-emerald-500"/></label><select value={filters.type} onChange={(event) => change('type',event.target.value)} className={selectClass}><option value="all">All types</option>{['HOTEL','TRANSPORT','DRIVER','ACTIVITY','GUIDE'].map((type) => <option key={type}>{type}</option>)}</select><select value={filters.status} onChange={(event) => change('status',event.target.value)} className={selectClass}><option value="all">All statuses</option><option>ACTIVE</option><option>INACTIVE</option></select><select value={filters.sort} onChange={(event) => change('sort',event.target.value)} className={selectClass}><option value="recent">Recently updated</option><option value="name">Name</option><option value="code">Vendor code</option></select></section>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <div className="hidden overflow-x-auto rounded-xl border border-slate-200 bg-white lg:block"><table className="w-full min-w-[1040px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['Vendor','Types','Primary contact','Location','Service areas','Status','Last updated',''].map((label) => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{!loading && vendors.map((vendor) => <tr key={vendor._id}><td className="px-4 py-4"><Link to={`/staff/operations/vendors/${vendor._id}`} className="font-semibold text-slate-950 hover:text-emerald-700">{vendor.name}</Link><p className="mt-1 font-mono text-xs text-slate-500">{vendor.vendorCode}</p></td><td className="px-4 py-4 text-xs text-slate-600">{vendor.types.join(', ')}</td><td className="px-4 py-4 text-xs text-slate-600"><p>{vendor.contact?.personName || '—'}</p><p>{vendor.contact?.phone || vendor.contact?.email || 'No contact'}</p></td><td className="px-4 py-4 text-xs text-slate-600">{[vendor.location?.city,vendor.location?.state].filter(Boolean).join(', ') || '—'}</td><td className="max-w-[220px] px-4 py-4 text-xs text-slate-600">{vendor.serviceAreas?.join(', ') || '—'}</td><td className="px-4 py-4"><OperationsStatusBadge value={vendor.status}/></td><td className="px-4 py-4 text-xs text-slate-600">{formatOperationsDate(vendor.updatedAt)}</td><td className="px-4 py-4"><Link to={`/staff/operations/vendors/${vendor._id}`} className="text-xs font-semibold text-emerald-700">View</Link></td></tr>)}{!loading && !vendors.length && <tr><td colSpan="8" className="px-4 py-12 text-center text-sm text-slate-500">No Vendors yet. Add your first Hotel, Transport Provider, Driver, Activity Provider or Guide.</td></tr>}{loading && <tr><td colSpan="8" className="px-4 py-12 text-center text-sm text-slate-500">Loading Vendor directory…</td></tr>}</tbody></table></div>
    <div className="grid gap-3 lg:hidden">{vendors.map((vendor) => <Link key={vendor._id} to={`/staff/operations/vendors/${vendor._id}`} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-950">{vendor.name}</p><p className="mt-1 font-mono text-xs text-slate-500">{vendor.vendorCode}</p></div><OperationsStatusBadge value={vendor.status}/></div><p className="mt-3 text-xs font-medium text-slate-700">{vendor.types.join(' · ')}</p><p className="mt-1 text-xs text-slate-500">{[vendor.location?.city,vendor.location?.state].filter(Boolean).join(', ') || 'Location not recorded'} · {vendor.contact?.phone || vendor.contact?.email || 'No contact'}</p><p className="mt-2 text-[11px] text-slate-400">Updated {formatOperationsDate(vendor.updatedAt)}</p></Link>)}{!loading && !vendors.length && <div className="rounded-xl border border-dashed border-slate-300 bg-white px-5 py-10 text-center text-sm text-slate-500">No Vendors yet. Add your first Hotel, Transport Provider, Driver, Activity Provider or Guide.</div>}</div>
    {!loading && pagination.pages > 0 && <footer className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><p className="text-slate-500">{pagination.total} Vendors · Page {pagination.page} of {pagination.pages}</p><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-slate-200 px-3 font-semibold disabled:opacity-40"><ChevronLeft size={15}/>Previous</button><button disabled={page >= pagination.pages} onClick={() => setPage((value) => value + 1)} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-slate-200 px-3 font-semibold disabled:opacity-40">Next<ChevronRight size={15}/></button></div></footer>}
  </div>;
}
