import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Edit3, ExternalLink, FileText, Loader2, Mail, MapPin, Phone, RefreshCw } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getOperationsVendorApi, updateOperationsVendorStatusApi } from '../../../../services/api.js';
import OperationsStatusBadge from '../components/OperationsStatusBadge.jsx';
import { formatOperationsDate, formatOperationsMoney } from '../helpers/operationsFormatters.js';

const Row = ({ label, value }) => <div className="grid grid-cols-[9rem_1fr] gap-3 border-b border-slate-100 py-2.5 text-sm last:border-0"><dt className="text-slate-500">{label}</dt><dd className="font-medium text-slate-800">{value || 'Not recorded'}</dd></div>;
export default function VendorDetail() {
  const { id } = useParams(); const [vendor, setVendor] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setVendor((await getOperationsVendorApi(id)).data); } catch (requestError) { setError(requestError.message || 'Unable to load Vendor.'); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]);
  const toggleStatus = async () => { setBusy(true); setError(''); try { setVendor((await updateOperationsVendorStatusApi(id, vendor.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE')).data); } catch (requestError) { setError(requestError.message || 'Unable to update Vendor status.'); } finally { setBusy(false); } };
  if (loading && !vendor) return <div className="flex min-h-72 items-center justify-center rounded-xl border border-slate-200 bg-white text-sm text-slate-500"><Loader2 className="mr-2 animate-spin" size={18}/>Loading Vendor…</div>;
  if (!vendor) return <div className="rounded-xl border border-rose-200 bg-white p-8 text-center text-sm text-rose-800">{error || 'Vendor not found.'}</div>;
  return <div className="space-y-5"><header className="rounded-xl border border-slate-200 bg-white p-5"><Link to="/staff/operations/vendors" className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-600"><ArrowLeft size={15}/>Vendor Directory</Link><div className="mt-4 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight text-slate-950">{vendor.name}</h1><OperationsStatusBadge value={vendor.status}/></div><p className="mt-2 font-mono text-xs text-slate-500">{vendor.vendorCode} · {vendor.types.join(' · ')}</p></div><div className="flex flex-wrap gap-2"><button onClick={load} className="flex h-10 w-10 items-center justify-center rounded-lg border border-slate-200 text-slate-600"><RefreshCw size={16}/></button><button onClick={toggleStatus} disabled={busy} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700 disabled:opacity-50">{vendor.status === 'ACTIVE' ? 'Mark inactive' : 'Reactivate'}</button><Link to={`/staff/operations/vendors/${id}/edit`} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white"><Edit3 size={15}/>Edit</Link></div></div></header>{error && <p className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Contact &amp; coverage</h2><dl className="mt-3"><Row label="Contact" value={vendor.contact?.personName}/><Row label="Phone" value={vendor.contact?.phone}/><Row label="WhatsApp" value={vendor.contact?.whatsapp}/><Row label="Email" value={vendor.contact?.email}/><Row label="Address" value={[vendor.location?.address,vendor.location?.city,vendor.location?.state,vendor.location?.pincode].filter(Boolean).join(', ')}/><Row label="Service areas" value={vendor.serviceAreas?.join(', ')}/></dl><div className="mt-4 flex flex-wrap gap-2">{vendor.contact?.phone && <a href={`tel:${vendor.contact.phone}`} className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-700"><Phone size={14}/>Call</a>}{vendor.contact?.email && <a href={`mailto:${vendor.contact.email}`} className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-700"><Mail size={14}/>Email</a>}{vendor.location?.city && <span className="inline-flex min-h-9 items-center gap-2 rounded-lg bg-slate-50 px-3 text-xs font-semibold text-slate-600"><MapPin size={14}/>{vendor.location.city}</span>}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Commercial reference</h2><dl className="mt-3"><Row label="Rate type" value={vendor.commercialReference?.rateType?.replaceAll('_',' ')}/><Row label="Reference rate" value={vendor.commercialReference?.defaultRate !== null && vendor.commercialReference?.defaultRate !== undefined ? formatOperationsMoney(vendor.commercialReference.defaultRate) : ''}/><Row label="Tax" value={vendor.commercialReference?.taxPercent !== null && vendor.commercialReference?.taxPercent !== undefined ? `${vendor.commercialReference.taxPercent}%` : ''}/><Row label="Payment terms" value={vendor.commercialReference?.paymentTerms}/><Row label="Used in services" value={String(vendor.serviceCount || 0)}/></dl><p className="mt-4 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600">These are operational reference terms only. Payout, expense and settlement workflows are deferred to Phase 4.</p></section></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Internal documents</h2>{vendor.documents?.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{vendor.documents.map((document) => <a key={document.documentId || document.secureUrl} href={document.secureUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-slate-200 p-3 text-sm font-medium text-slate-700"><span className="flex min-w-0 items-center gap-2"><FileText size={16}/><span className="min-w-0"><span className="block truncate">{document.title || document.fileName}</span><span className="mt-0.5 block text-[11px] font-normal text-slate-500">{document.type?.replaceAll('_',' ')}{document.expiryDate ? ` · Expires ${formatOperationsDate(document.expiryDate)}` : ''}</span></span></span><ExternalLink size={14}/></a>)}</div> : <p className="mt-3 text-sm text-slate-500">No internal documents uploaded.</p>}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Recent operational usage</h2>{vendor.recentServices?.length ? <div className="mt-4 divide-y divide-slate-100 rounded-lg border border-slate-200">{vendor.recentServices.map((service) => <div key={service._id} className="flex items-center justify-between gap-3 p-3"><div><p className="text-sm font-semibold text-slate-900">{service.title}</p><p className="mt-1 text-xs text-slate-500">{service.serviceType} · Updated {formatOperationsDate(service.updatedAt)}</p></div><OperationsStatusBadge value={service.confirmationStatus}/></div>)}</div> : <p className="mt-3 text-sm text-slate-500">This Vendor has not been assigned to an operational service yet.</p>}</section>
    {vendor.notes && <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Internal notes</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{vendor.notes}</p></section>}
  </div>;
}
