import React, { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertCircle, Edit3, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { deleteCampaignApi, getCampaignsApi } from '../../../../services/api';
import { getApiErrorMessage } from '../../../../services/apiConfig';
import { CAMPAIGN_STATUSES, CAMPAIGN_TYPES, formatDate, formatMoney, MarketingEmptyState, StatusBadge, titleCase } from '../marketingHelpers';

export default function CampaignsWorkspace() {
  const [records, setRecords] = useState([]); const [pagination, setPagination] = useState({ page: 1, pages: 1, total: 0 }); const [filters, setFilters] = useState({ search: '', status: 'all', type: 'all', from: '', to: '' }); const [query, setQuery] = useState(filters); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await getCampaignsApi({ ...query, page: pagination.page, limit: 25 }); setRecords(data.campaigns || []); setPagination((current) => ({ ...data.pagination, page: data.pagination?.page || current.page })); } catch (err) { setError(getApiErrorMessage(err, 'Unable to load campaigns.')); } finally { setLoading(false); } }, [query, pagination.page]);
  useEffect(() => { load(); }, [load]);
  const remove = async (record) => { if (!window.confirm(`Delete campaign “${record.name}”?`)) return; try { await deleteCampaignApi(record._id); await load(); } catch (err) { setError(getApiErrorMessage(err, 'Unable to delete the campaign.')); } };
  const apply = (event) => { event.preventDefault(); setPagination((value) => ({ ...value, page: 1 })); setQuery(filters); };
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Marketing</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Campaigns</h1><p className="mt-2 text-sm text-slate-600">Plan campaign schedules, budgets, audiences, and attribution parameters.</p></div><Link to="/staff/marketing/campaigns/new" className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white hover:bg-slate-800"><Plus size={16}/>New campaign</Link></header>
    <form onSubmit={apply} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_150px_150px_150px_150px_auto]"><label className="relative"><span className="sr-only">Search campaigns</span><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Search name, code, audience" className="min-h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-emerald-500"/></label><select aria-label="Campaign status" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="all">All statuses</option>{CAMPAIGN_STATUSES.map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</select><select aria-label="Campaign type" value={filters.type} onChange={(e) => setFilters({ ...filters, type: e.target.value })} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="all">All types</option>{CAMPAIGN_TYPES.map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</select><input aria-label="Campaigns from date" type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"/><input aria-label="Campaigns to date" type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"/><button className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50">Apply</button></form>
    {error && <div className="flex items-center gap-2 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={16}/>{error}</div>}
    {loading ? <div className="flex justify-center py-16 text-slate-500"><RefreshCw className="animate-spin"/></div> : !records.length ? <MarketingEmptyState title="No campaigns found" description="Create a campaign or adjust the current filters." action={<Link to="/staff/marketing/campaigns/new" className="mt-4 inline-flex rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Create campaign</Link>}/> : <>
      <div className="hidden overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Type / Audience</th><th className="px-4 py-3">Schedule</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-slate-100">{records.map((record) => <tr key={record._id} className="hover:bg-slate-50"><td className="px-4 py-3"><p className="font-semibold text-slate-900">{record.name}</p><p className="text-xs text-slate-500">{record.code} · {formatMoney(record.budget)}</p></td><td className="px-4 py-3"><p className="text-slate-700">{titleCase(record.type)}</p><p className="max-w-[180px] truncate text-xs text-slate-500">{record.targetAudience || 'All audiences'}</p></td><td className="px-4 py-3 text-xs text-slate-600">{formatDate(record.startDate)} — {formatDate(record.endDate)}</td><td className="px-4 py-3"><StatusBadge status={record.displayStatus || record.status}/></td><td className="px-4 py-3 text-xs text-slate-600">{formatDate(record.updatedAt)}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link aria-label={`Edit ${record.name}`} to={`/staff/marketing/campaigns/${record._id}/edit`} className="rounded-md p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-900"><Edit3 size={15}/></Link><button type="button" aria-label={`Delete ${record.name}`} onClick={() => remove(record)} className="rounded-md p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-700"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>
      <div className="space-y-3 md:hidden">{records.map((record) => <article key={record._id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-900">{record.name}</h2><p className="mt-0.5 text-xs text-slate-500">{record.code} · {titleCase(record.type)}</p></div><StatusBadge status={record.displayStatus || record.status}/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-400">Schedule</dt><dd className="mt-1 text-slate-700">{formatDate(record.startDate)} — {formatDate(record.endDate)}</dd></div><div><dt className="text-slate-400">Budget</dt><dd className="mt-1 font-medium text-slate-800">{formatMoney(record.budget)}</dd></div></dl><div className="mt-4 flex gap-2"><Link to={`/staff/marketing/campaigns/${record._id}/edit`} className="flex-1 rounded-lg border border-slate-200 py-2 text-center text-sm font-semibold text-slate-700">Edit</Link><button onClick={() => remove(record)} className="rounded-lg border border-slate-200 px-3 text-rose-700"><Trash2 size={15}/></button></div></article>)}</div>
      <div className="flex items-center justify-between text-sm text-slate-500"><span>{pagination.total} campaign{pagination.total === 1 ? '' : 's'}</span><div className="flex gap-2"><button disabled={pagination.page <= 1} onClick={() => setPagination((value) => ({ ...value, page: value.page - 1 }))} className="rounded-lg border border-slate-200 px-3 py-2 disabled:opacity-40">Previous</button><button disabled={pagination.page >= pagination.pages} onClick={() => setPagination((value) => ({ ...value, page: value.page + 1 }))} className="rounded-lg border border-slate-200 px-3 py-2 disabled:opacity-40">Next</button></div></div>
    </>}
  </div>;
}
