import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { AlertCircle, ArrowLeft, Save } from 'lucide-react';
import { createCampaignApi, getCampaignByIdApi, updateCampaignApi } from '../../../../services/api';
import { getApiErrorMessage } from '../../../../services/apiConfig';
import { CAMPAIGN_STATUSES, CAMPAIGN_TYPES, titleCase, toDateInput } from '../marketingHelpers';

const empty = { name: '', code: '', type: 'other', status: 'draft', startDate: '', endDate: '', budget: 0, targetAudience: '', utmSource: '', utmMedium: '', utmCampaign: '', targetDestinations: '', featuredTrips: '', notes: '' };
const Field = ({ label, children, hint }) => <label className="block"><span className="text-xs font-semibold text-slate-700">{label}</span>{children}{hint && <span className="mt-1 block text-xs text-slate-400">{hint}</span>}</label>;
const inputClass = 'mt-1 min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10';

export default function CampaignEditor() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [form, setForm] = useState(empty); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!id) return; getCampaignByIdApi(id).then(({ campaign }) => setForm({ ...empty, ...campaign, startDate: toDateInput(campaign.startDate), endDate: toDateInput(campaign.endDate), targetDestinations: (campaign.targetDestinations || []).join(', '), featuredTrips: (campaign.featuredTrips || []).join(', ') })).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [id]);
  const change = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, budget: Number(form.budget), targetDestinations: form.targetDestinations.split(',').map((v) => v.trim()).filter(Boolean), featuredTrips: form.featuredTrips.split(',').map((v) => v.trim()).filter(Boolean) }; if (editing) await updateCampaignApi(id, payload); else await createCampaignApi(payload); navigate('/staff/marketing/campaigns'); } catch (err) { setError(getApiErrorMessage(err, 'Unable to save the campaign.')); } finally { setSaving(false); } };
  if (loading) return <div className="py-20 text-center text-sm text-slate-500">Loading campaign…</div>;
  return <form onSubmit={submit} className="space-y-6"><header className="flex items-start gap-3"><Link to="/staff/marketing/campaigns" className="mt-1 rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"><ArrowLeft size={16}/></Link><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Campaigns</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{editing ? 'Edit campaign' : 'New campaign'}</h1><p className="mt-1 text-sm text-slate-600">Configure the operational record. Performance analytics are not inferred here.</p></div></header>{error && <div className="flex items-center gap-2 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle size={16}/>{error}</div>}
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-950">Campaign identity</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Name"><input required value={form.name} onChange={change('name')} className={inputClass}/></Field><Field label="Campaign code"><input required value={form.code} onChange={change('code')} className={`${inputClass} uppercase`} placeholder="AUTUMN-2026"/></Field><Field label="Type"><select value={form.type} onChange={change('type')} className={inputClass}>{CAMPAIGN_TYPES.map((v) => <option key={v} value={v}>{titleCase(v)}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={change('status')} className={inputClass}>{CAMPAIGN_STATUSES.map((v) => <option key={v} value={v}>{titleCase(v)}</option>)}</select></Field><Field label="Target audience"><input value={form.targetAudience} onChange={change('targetAudience')} className={inputClass} placeholder="e.g. Young professionals in Bengaluru"/></Field><Field label="Budget (INR)"><input type="number" min="0" step="1" value={form.budget} onChange={change('budget')} className={inputClass}/></Field><Field label="Start date"><input type="date" value={form.startDate} onChange={change('startDate')} className={inputClass}/></Field><Field label="End date"><input type="date" value={form.endDate} onChange={change('endDate')} className={inputClass}/></Field></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-950">Attribution and scope</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="UTM source"><input value={form.utmSource} onChange={change('utmSource')} className={inputClass}/></Field><Field label="UTM medium"><input value={form.utmMedium} onChange={change('utmMedium')} className={inputClass}/></Field><Field label="UTM campaign"><input value={form.utmCampaign} onChange={change('utmCampaign')} className={inputClass}/></Field><div className="md:col-span-3 grid gap-4 md:grid-cols-2"><Field label="Target destinations" hint="Comma-separated destination names."><input value={form.targetDestinations} onChange={change('targetDestinations')} className={inputClass}/></Field><Field label="Featured trip references" hint="Comma-separated trip IDs or slugs."><input value={form.featuredTrips} onChange={change('featuredTrips')} className={inputClass}/></Field></div><div className="md:col-span-3"><Field label="Notes"><textarea rows="4" value={form.notes} onChange={change('notes')} className={`${inputClass} py-2`}/></Field></div></div></section>
    <div className="flex justify-end gap-3"><Link to="/staff/marketing/campaigns" className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</Link><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={16}/>{saving ? 'Saving…' : 'Save campaign'}</button></div>
  </form>;
}
