import { useState } from 'react';
import OperationsDialog from './OperationsDialog.jsx';

export default function CommunicationFormModal({ bookings = [], services = [], incidents = [], tasks = [], defaultIncidentId = '', onClose, onSave }) {
  const [form, setForm] = useState({ direction: 'OUTBOUND', channel: 'PHONE', communicationType: defaultIncidentId ? 'EMERGENCY_UPDATE' : 'GENERAL_UPDATE', bookingId: '', occurredAt: '', summary: '', details: '', relatedServiceId: '', relatedIncidentId: defaultIncidentId, relatedTaskId: '' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const update = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await onSave({ ...form, occurredAt: form.occurredAt ? new Date(form.occurredAt).toISOString() : undefined }); onClose(); } catch (requestError) { setError(requestError.message || 'Unable to record the update.'); } finally { setBusy(false); } };
  const field = 'mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500';
  return <OperationsDialog title="Log Customer Update" description="Record a communication that already occurred. This does not send a message." onClose={onClose} wide footer={<><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700">Cancel</button><button form="communication-form" disabled={busy} className="min-h-10 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Recording…' : 'Record communication'}</button></>}>
    <form id="communication-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Direction<select value={form.direction} onChange={update('direction')} className={field}><option>OUTBOUND</option><option>INBOUND</option></select></label><label className="text-sm font-medium text-slate-700">Channel<select value={form.channel} onChange={update('channel')} className={field}>{['PHONE','WHATSAPP','EMAIL','SMS','IN_PERSON','OTHER'].map((value) => <option key={value}>{value}</option>)}</select></label>
      <label className="text-sm font-medium text-slate-700">Update type<select value={form.communicationType} onChange={update('communicationType')} className={field}>{['GENERAL_UPDATE','PICKUP_DETAILS','DRIVER_DETAILS','ITINERARY_UPDATE','HOTEL_CHANGE','TRANSPORT_CHANGE','ACTIVITY_UPDATE','PRE_DEPARTURE_CONFIRMATION','CUSTOMER_QUERY','CUSTOMER_COMPLAINT','EMERGENCY_UPDATE','OTHER'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Audience<select value={form.bookingId} onChange={update('bookingId')} className={field}><option value="">Whole departure</option>{bookings.map((booking) => <option key={booking._id} value={booking._id}>{booking.bookingId} · {booking.customer?.name || 'Traveler'}</option>)}</select></label>
      <label className="text-sm font-medium text-slate-700">Occurred at<input type="datetime-local" value={form.occurredAt} onChange={update('occurredAt')} className={field}/><span className="mt-1 block text-xs font-normal text-slate-500">Leave blank to use the current time.</span></label><label className="text-sm font-medium text-slate-700">Related service<select value={form.relatedServiceId} onChange={update('relatedServiceId')} className={field}><option value="">None</option>{services.map((service) => <option key={service._id} value={service._id}>{service.serviceType} · {service.title}</option>)}</select></label>
      <label className="sm:col-span-2 text-sm font-medium text-slate-700">Summary<input required maxLength="500" autoFocus value={form.summary} onChange={update('summary')} placeholder="Traveler confirmed the revised pickup point." className={field}/></label><label className="sm:col-span-2 text-sm font-medium text-slate-700">Details<textarea rows="3" maxLength="3000" value={form.details} onChange={update('details')} className={`${field} py-2`}/></label>
      <label className="text-sm font-medium text-slate-700">Related incident<select value={form.relatedIncidentId} onChange={update('relatedIncidentId')} className={field}><option value="">None</option>{incidents.map((incident) => <option key={incident._id} value={incident._id}>{incident.incidentCode} · {incident.title}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Related task<select value={form.relatedTaskId} onChange={update('relatedTaskId')} className={field}><option value="">None</option>{tasks.map((task) => <option key={task._id} value={task._id}>{task.title}</option>)}</select></label>{error && <p role="alert" className="sm:col-span-2 text-sm text-rose-700">{error}</p>}
    </form>
  </OperationsDialog>;
}
