import { useState } from 'react';
import { Paperclip } from 'lucide-react';
import { uploadOperationsDocumentApi } from '../../../../services/api.js';
import OperationsDialog from './OperationsDialog.jsx';

export default function IncidentFormModal({ bookings = [], services = [], coordinators = [], onClose, onSave }) {
  const [form, setForm] = useState({ title: '', incidentType: 'OTHER', severity: 'MEDIUM', scope: 'TRIP_WIDE', bookingId: '', linkedServiceId: '', description: '', assignedTo: '', reportedAt: '', documents: [] });
  const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const update = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); try { const response = await uploadOperationsDocumentApi(file, { type: 'INCIDENT_EVIDENCE', title: file.name }); setForm((value) => ({ ...value, documents: [...value.documents, response.data] })); } catch (requestError) { setError(requestError.message || 'Unable to upload evidence.'); } finally { setUploading(false); event.target.value = ''; } };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await onSave({ ...form, bookingId: form.scope === 'BOOKING' ? form.bookingId : '', linkedServiceId: form.scope === 'SERVICE' ? form.linkedServiceId : '', reportedAt: form.reportedAt ? new Date(form.reportedAt).toISOString() : undefined }); onClose(); } catch (requestError) { setError(requestError.message || 'Unable to report the issue.'); } finally { setBusy(false); } };
  const field = 'mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500';
  return <OperationsDialog title="Report Issue" description="Record factual operational details only. Do not include unnecessary medical information." onClose={onClose} wide footer={<><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700">Cancel</button><button form="incident-form" disabled={busy || uploading} className="min-h-10 rounded-lg bg-rose-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Reporting…' : 'Report issue'}</button></>}>
    <form id="incident-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium text-slate-700">Title<input required maxLength="220" autoFocus value={form.title} onChange={update('title')} className={field}/></label><label className="text-sm font-medium text-slate-700">Type<select value={form.incidentType} onChange={update('incidentType')} className={field}>{['CUSTOMER_COMPLAINT','SERVICE_FAILURE','DELAY','HOTEL_ISSUE','TRANSPORT_ISSUE','VEHICLE_BREAKDOWN','ACTIVITY_ISSUE','CANCELLATION','WEATHER_DISRUPTION','ROAD_CLOSURE','MEDICAL_EMERGENCY','SAFETY_EMERGENCY','LOST_ITEM','OTHER'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Severity<select value={form.severity} onChange={update('severity')} className={field}>{['LOW','MEDIUM','HIGH','CRITICAL'].map((value) => <option key={value}>{value}</option>)}</select></label>
      <label className="text-sm font-medium text-slate-700">Scope<select value={form.scope} onChange={update('scope')} className={field}><option value="TRIP_WIDE">Whole departure</option><option value="BOOKING">Specific booking</option><option value="SERVICE">Specific service</option></select></label>{form.scope === 'BOOKING' && <label className="text-sm font-medium text-slate-700">Booking<select required value={form.bookingId} onChange={update('bookingId')} className={field}><option value="">Select booking</option>{bookings.map((booking) => <option key={booking._id} value={booking._id}>{booking.bookingId} · {booking.customer?.name}</option>)}</select></label>}{form.scope === 'SERVICE' && <label className="text-sm font-medium text-slate-700">Service<select required value={form.linkedServiceId} onChange={update('linkedServiceId')} className={field}><option value="">Select service</option>{services.map((service) => <option key={service._id} value={service._id}>{service.serviceType} · {service.title}</option>)}</select></label>}
      <label className="text-sm font-medium text-slate-700">Assign to<select value={form.assignedTo} onChange={update('assignedTo')} className={field}><option value="">Unassigned</option>{coordinators.map((person) => <option key={person._id} value={person._id}>{person.name} · {person.role}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Reported at<input type="datetime-local" value={form.reportedAt} onChange={update('reportedAt')} className={field}/></label>
      <label className="sm:col-span-2 text-sm font-medium text-slate-700">Description<textarea required rows="4" maxLength="5000" value={form.description} onChange={update('description')} placeholder="Describe what happened and the current operational impact." className={`${field} py-2`}/></label><label className="sm:col-span-2 text-sm font-medium text-slate-700">Evidence (optional)<span className="mt-1.5 flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-slate-300 text-sm text-slate-600"><Paperclip size={15}/>{uploading ? 'Uploading…' : 'Attach PDF or image'}<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="sr-only" onChange={upload} disabled={uploading}/></span>{form.documents.length > 0 && <span className="mt-2 block text-xs font-normal text-emerald-700">{form.documents.length} file(s) attached</span>}</label>{error && <p role="alert" className="sm:col-span-2 text-sm text-rose-700">{error}</p>}
    </form>
  </OperationsDialog>;
}
