import React from 'react';
import { Loader2, X } from 'lucide-react';
import { formatQuotationDate, formatQuotationMoney } from '../../quotations/quotationHelpers.js';

const Item = ({ label, value }) => <div className="flex justify-between gap-4 border-b border-slate-100 py-2.5 last:border-0"><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="text-right text-sm font-medium text-slate-900">{value || '—'}</dd></div>;

const CreateBookingModal = ({ quotation, open, busy, error, onClose, onConfirm }) => {
  if (!open || !quotation) return null;
  return <div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><button type="button" onClick={busy ? undefined : onClose} className="absolute inset-0 bg-slate-950/60" aria-label="Close booking confirmation" /><section role="dialog" aria-modal="true" aria-labelledby="create-booking-title" className="relative z-10 w-full max-w-lg rounded-xl border border-slate-200 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">Commercial handoff</p><h2 id="create-booking-title" className="mt-1 text-xl font-semibold tracking-tight text-slate-950">Create booking</h2><p className="mt-2 text-sm leading-6 text-slate-600">Create one pending-payment booking from this approved quotation.</p></div><button type="button" onClick={onClose} disabled={busy} className="flex h-10 w-10 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Close"><X size={18} /></button></div><dl className="mt-4 rounded-lg border border-slate-200 px-4"><Item label="Traveler" value={quotation.customerSnapshot?.name} /><Item label="Quotation" value={quotation.quotationNumber} /><Item label="Trip" value={quotation.tripRequirements?.title} /><Item label="Travel dates" value={`${formatQuotationDate(quotation.tripRequirements?.startDate)} – ${formatQuotationDate(quotation.tripRequirements?.endDate)}`} /><Item label="Total amount" value={formatQuotationMoney(quotation.pricing?.finalTotal)} /><Item label="Deposit due" value={formatQuotationMoney(quotation.pricing?.depositRequired)} /></dl>{error && <p className="mt-4 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={busy} className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700">Cancel</button><button type="button" onClick={onConfirm} disabled={busy} className="flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white hover:bg-emerald-500 disabled:opacity-60">{busy && <Loader2 size={15} className="animate-spin" />}Confirm &amp; create booking</button></div></section></div>;
};

export default CreateBookingModal;
