import React from 'react';
import PaymentStatusBadge from './PaymentStatusBadge.jsx';
import { formatBookingDate, formatBookingMoney, getAmountRemaining } from '../bookingAdminHelpers.js';

const Row = ({ label, value }) => <div className="grid grid-cols-[minmax(8rem,0.8fr)_minmax(0,1.2fr)] gap-3 border-b border-slate-100 py-2.5 last:border-0"><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="break-all text-sm text-slate-800">{value ?? '—'}</dd></div>;
const BookingPaymentSection = ({ booking }) => {
  const payments = booking.payments || [];
  const currency = booking.pricing?.currency;
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-950">Payment</h2><PaymentStatusBadge status={booking.paymentStatus} /></div><dl className="mt-3"><Row label="Subtotal" value={formatBookingMoney(booking.pricing?.subtotal, currency)} /><Row label="Discount" value={formatBookingMoney(booking.pricing?.discount, currency)} /><Row label="Taxes / fees" value={formatBookingMoney(booking.pricing?.taxes, currency)} /><Row label="Total" value={formatBookingMoney(booking.pricing?.finalAmount, currency)} /><Row label="Paid" value={formatBookingMoney(booking.pricing?.amountPaid, currency)} /><Row label="Remaining" value={formatBookingMoney(getAmountRemaining(booking), currency)} /><Row label="Payment plan" value={booking.paymentPlan?.type} /><Row label="Balance due" value={formatBookingDate(booking.pricing?.balanceDueDate)} /><Row label="Provider" value={booking.payment?.provider} /><Row label="Gateway status" value={booking.payment?.status || 'Unknown'} /><Row label="Razorpay order ID" value={booking.payment?.razorpayOrderId} /><Row label="Razorpay payment ID" value={booking.payment?.razorpayPaymentId} /><Row label="Paid at" value={formatBookingDate(booking.payment?.paidAt, true)} /></dl><div className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Payment events</h3>{payments.length ? <div className="mt-2 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-2">Date</th><th className="px-3 py-2">Amount</th><th className="px-3 py-2">Type</th><th className="px-3 py-2">Order</th><th className="px-3 py-2">Payment reference</th><th className="px-3 py-2">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((payment, index) => <tr key={payment._id || `${payment.orderId}-${index}`}><td className="px-3 py-2 text-slate-600">{formatBookingDate(payment.verifiedAt, true)}</td><td className="px-3 py-2 font-semibold">{formatBookingMoney(payment.amount, currency)}</td><td className="px-3 py-2">{payment.type || '—'}</td><td className="px-3 py-2 font-mono text-xs">{payment.orderId || '—'}</td><td className="px-3 py-2 font-mono text-xs">{payment.paymentId || '—'}</td><td className="px-3 py-2">{payment.verifiedAt ? 'Verified' : 'Unknown'}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-slate-500">No persisted payment events.</p>}</div></section>;
};

export default BookingPaymentSection;
