import React, { useState } from 'react';
import { AlertTriangle, X } from 'lucide-react';
import BookingStatusBadge from './BookingStatusBadge.jsx';

const CancelBookingModal = ({ booking, open, busy, onClose, onConfirm }) => {
  const [reason, setReason] = useState('');
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/65 p-4" role="dialog" aria-modal="true" aria-labelledby="cancel-booking-title"><div className="w-full max-w-lg rounded-xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-rose-50 text-rose-700"><AlertTriangle size={19} /></span><div><h2 id="cancel-booking-title" className="font-semibold text-slate-950">Cancel booking</h2><p className="mt-1 font-mono text-xs text-slate-500">{booking.bookingId}</p></div></div><button type="button" onClick={onClose} className="h-9 w-9 rounded-lg text-slate-500 hover:bg-slate-100"><X size={17} className="mx-auto" /></button></div><div className="space-y-4 p-5"><div className="grid gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm sm:grid-cols-2"><p><span className="text-slate-500">Traveler:</span> <span className="font-medium">{booking.customer?.name || '—'}</span></p><p><span className="text-slate-500">Trip:</span> <span className="font-medium">{booking.tripSnapshot?.title || '—'}</span></p><p className="flex items-center gap-2"><span className="text-slate-500">Payment:</span><BookingStatusBadge status={booking.paymentStatus} /></p></div><label className="block text-sm font-medium text-slate-700"><span>Cancellation reason</span><textarea rows="4" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Record the operational reason…" className="mt-1.5 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-rose-400" /></label>{['PAID', 'PARTIALLY_PAID'].includes(booking.paymentStatus) && <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Cancellation does not process a refund. Payment and refund handling remain separate.</p>}</div><div className="flex justify-end gap-2 border-t border-slate-200 p-4"><button type="button" onClick={onClose} disabled={busy} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700">Keep booking</button><button type="button" onClick={() => onConfirm(reason)} disabled={busy || !reason.trim()} className="min-h-10 rounded-lg bg-rose-700 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Cancelling…' : 'Confirm cancellation'}</button></div></div></div>;
};

export default CancelBookingModal;
