import React from 'react';

const Metric = ({ label, value }) => <div className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-[11px] font-medium uppercase tracking-[0.06em] text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold text-slate-950">{value ?? '—'}</p></div>;
const MediaCoveragePanel = ({ coverage }) => {
  if (!coverage) return null;
  const metrics = coverage.metrics || {};
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 className="text-sm font-semibold text-slate-950">Media coverage</h2><p className="mt-1 text-xs text-slate-500">Calculated from active MongoDB assets and current Trip destinations/itinerary locations.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Active assets" value={metrics.totalAssets} /><Metric label="Trip locations" value={metrics.totalLocations} /><Metric label="Covered" value={metrics.exactCount} /><Metric label="Missing" value={metrics.missingCount} /><Metric label="Coverage" value={`${metrics.coveragePercentage ?? 0}%`} /></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Assets by destination</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(coverage.byDestination || {}).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([label, count]) => <span key={label} className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-700">{label} · {count}</span>)}</div></div><div><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Assets by category</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(coverage.byCategory || {}).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([label, count]) => <span key={label} className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-700">{label} · {count}</span>)}</div></div></div>{coverage.missingQueue?.length > 0 && <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Missing coverage</p><div className="mt-2 flex flex-wrap gap-2">{coverage.missingQueue.slice(0, 12).map((item) => <span key={`${item.destination}-${item.location}`} className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-xs text-amber-900">{item.location} · {item.destination}</span>)}</div></div>}</section>;
};

export default MediaCoveragePanel;
