import React from 'react';
import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react';

const inputClass = 'min-h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500';
const TextList = ({ title, values, onChange }) => <div className="space-y-2"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-900">{title}</h3><button type="button" onClick={() => onChange([...values, ''])} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 text-xs font-semibold"><Plus size={14} />Add</button></div>{values.map((item, index) => <div key={index} className="flex gap-2"><input className={inputClass} value={item} onChange={(e) => onChange(values.map((value, idx) => idx === index ? e.target.value : value))} /><button type="button" onClick={() => onChange(values.filter((_, idx) => idx !== index))} className="h-10 w-10 shrink-0 rounded-lg border border-slate-200 text-slate-500 hover:text-rose-600"><Trash2 size={15} className="mx-auto" /></button></div>)}</div>;

const TripContentForm = ({ value, onChange }) => {
  const set = (field, next) => onChange({ ...value, [field]: next });
  const moveDay = (index, direction) => { const next = [...value.itinerary]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; set('itinerary', next); };
  return <div className="space-y-7">
    <div className="grid gap-4"><label className="space-y-1.5 text-sm font-medium text-slate-700"><span>Short description</span><textarea rows="3" className={`${inputClass} py-2`} value={value.shortDescription} onChange={(e) => set('shortDescription', e.target.value)} /></label><label className="space-y-1.5 text-sm font-medium text-slate-700"><span>Overview</span><textarea rows="7" className={`${inputClass} py-2`} value={value.overview} onChange={(e) => set('overview', e.target.value)} /></label></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-slate-900">Itinerary</h3><p className="text-xs text-slate-500">Day, title and description use the existing itinerary structure.</p></div><button type="button" onClick={() => set('itinerary', [...value.itinerary, { day: value.itinerary.length + 1, title: '', description: '' }])} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 text-xs font-semibold"><Plus size={14} />Add day</button></div>{value.itinerary.map((day, index) => <div key={index} className="grid gap-2 rounded-lg border border-slate-200 p-3 md:grid-cols-[80px_1fr_auto]"><input type="number" min="1" className={inputClass} value={day.day ?? index + 1} onChange={(e) => set('itinerary', value.itinerary.map((item, idx) => idx === index ? { ...item, day: e.target.value } : item))} /><div className="space-y-2"><input className={inputClass} placeholder="Day title" value={day.title || ''} onChange={(e) => set('itinerary', value.itinerary.map((item, idx) => idx === index ? { ...item, title: e.target.value } : item))} /><textarea rows="3" className={`${inputClass} py-2`} placeholder="Description" value={day.description || day.activities || ''} onChange={(e) => set('itinerary', value.itinerary.map((item, idx) => idx === index ? { ...item, description: e.target.value } : item))} /></div><div className="flex gap-1 md:flex-col"><button type="button" onClick={() => moveDay(index, -1)} className="h-9 w-9 rounded-lg border border-slate-200"><ArrowUp size={14} className="mx-auto" /></button><button type="button" onClick={() => moveDay(index, 1)} className="h-9 w-9 rounded-lg border border-slate-200"><ArrowDown size={14} className="mx-auto" /></button><button type="button" onClick={() => set('itinerary', value.itinerary.filter((_, idx) => idx !== index))} className="h-9 w-9 rounded-lg border border-slate-200 text-rose-600"><Trash2 size={14} className="mx-auto" /></button></div></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><TextList title="Inclusions" values={value.inclusions} onChange={(next) => set('inclusions', next)} /><TextList title="Exclusions" values={value.exclusions} onChange={(next) => set('exclusions', next)} /><TextList title="Pickup points" values={value.pickupPoints} onChange={(next) => set('pickupPoints', next)} /></div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-900">FAQs</h3><button type="button" onClick={() => set('faqs', [...value.faqs, { question: '', answer: '' }])} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 text-xs font-semibold"><Plus size={14} />Add FAQ</button></div>{value.faqs.map((faq, index) => <div key={index} className="grid gap-2 rounded-lg border border-slate-200 p-3 md:grid-cols-[1fr_1fr_auto]"><input className={inputClass} placeholder="Question" value={faq.question || ''} onChange={(e) => set('faqs', value.faqs.map((item, idx) => idx === index ? { ...item, question: e.target.value } : item))} /><textarea rows="2" className={`${inputClass} py-2`} placeholder="Answer" value={faq.answer || ''} onChange={(e) => set('faqs', value.faqs.map((item, idx) => idx === index ? { ...item, answer: e.target.value } : item))} /><button type="button" onClick={() => set('faqs', value.faqs.filter((_, idx) => idx !== index))} className="h-10 w-10 rounded-lg border border-slate-200 text-rose-600"><Trash2 size={14} className="mx-auto" /></button></div>)}</div>
  </div>;
};

export default TripContentForm;

