import { useMemo, useState } from 'react';
import { FileUp, Loader2, X } from 'lucide-react';
import { uploadOperationsDocumentApi } from '../../../../../services/api.js';

const inputClass = 'mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 text-sm text-slate-800 outline-none focus:border-emerald-500';
const dateValue = (value) => value ? new Date(value).toISOString().slice(0, 10) : '';
const numberValue = (value) => value === '' || value === null || value === undefined ? null : Number(value);
const serviceDocumentTypes = (type) => type === 'HOTEL' ? ['HOTEL_VOUCHER', 'CONFIRMATION', 'OTHER'] : type === 'TRANSPORT' ? ['TRANSPORT_VOUCHER', 'DRIVER_DOCUMENT', 'CONFIRMATION', 'OTHER'] : type === 'ACTIVITY' ? ['ACTIVITY_TICKET', 'CONFIRMATION', 'OTHER'] : ['CONFIRMATION', 'OTHER'];

const initialForm = (service, type) => ({
  serviceType: service?.serviceType || type || 'HOTEL', title: service?.title || '', required: service?.required ?? true,
  bookingReference: service?.bookingReference || '', internalNotes: service?.internalNotes || '', documents: service?.documents || [],
  schedule: { startDate: dateValue(service?.schedule?.startDate), startTime: service?.schedule?.startTime || '', endDate: dateValue(service?.schedule?.endDate), endTime: service?.schedule?.endTime || '' },
  hotelDetails: { hotelName: service?.hotelDetails?.hotelName || '', city: service?.hotelDetails?.city || '', address: service?.hotelDetails?.address || '', roomType: service?.hotelDetails?.roomType || '', rooms: service?.hotelDetails?.rooms ?? '', occupancy: service?.hotelDetails?.occupancy || '', mealPlan: service?.hotelDetails?.mealPlan || '', checkIn: dateValue(service?.hotelDetails?.checkIn), checkOut: dateValue(service?.hotelDetails?.checkOut), nights: service?.hotelDetails?.nights ?? '' },
  transportDetails: { mode: service?.transportDetails?.mode || '', vehicleType: service?.transportDetails?.vehicleType || '', vehicleNumber: service?.transportDetails?.vehicleNumber || '', capacity: service?.transportDetails?.capacity ?? '', route: { from: service?.transportDetails?.route?.from || '', to: service?.transportDetails?.route?.to || '', pickupPoint: service?.transportDetails?.route?.pickupPoint || '', dropPoint: service?.transportDetails?.route?.dropPoint || '' }, departureDate: dateValue(service?.transportDetails?.departureDate), departureTime: service?.transportDetails?.departureTime || '', arrivalDate: dateValue(service?.transportDetails?.arrivalDate), arrivalTime: service?.transportDetails?.arrivalTime || '' },
  activityDetails: { activityName: service?.activityDetails?.activityName || '', location: service?.activityDetails?.location || '', date: dateValue(service?.activityDetails?.date), startTime: service?.activityDetails?.startTime || '', endTime: service?.activityDetails?.endTime || '', travelerCount: service?.activityDetails?.travelerCount ?? '', meetingPoint: service?.activityDetails?.meetingPoint || '', dayNumber: service?.activityDetails?.dayNumber ?? '' },
  guideDetails: { guideName: service?.guideDetails?.guideName || '', phone: service?.guideDetails?.phone || '', date: dateValue(service?.guideDetails?.date), startTime: service?.guideDetails?.startTime || '', endTime: service?.guideDetails?.endTime || '', location: service?.guideDetails?.location || '', language: service?.guideDetails?.language || '', meetingPoint: service?.guideDetails?.meetingPoint || '' }
});

const Field = ({ label, children, wide = false }) => <label className={`text-sm font-medium text-slate-700 ${wide ? 'sm:col-span-2' : ''}`}>{label}{children}</label>;
const Text = ({ value, onChange, ...props }) => <input {...props} value={value} onChange={(event) => onChange(event.target.value)} className={inputClass}/>;

export default function ServiceEditorModal({ service, initialType, busy, onClose, onSave }) {
  const [form, setForm] = useState(() => initialForm(service, initialType));
  const [uploading, setUploading] = useState(false);
  const [documentType, setDocumentType] = useState(() => serviceDocumentTypes(service?.serviceType || initialType || 'HOTEL')[0]);
  const [documentExpiry, setDocumentExpiry] = useState('');
  const [error, setError] = useState('');
  const type = form.serviceType;
  const title = service ? 'Edit operational service' : 'Add operational service';
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const setNested = (key, child, value) => setForm((current) => ({ ...current, [key]: { ...current[key], [child]: value } }));
  const setRoute = (child, value) => setForm((current) => ({ ...current, transportDetails: { ...current.transportDetails, route: { ...current.transportDetails.route, [child]: value } } }));
  const documentTypes = useMemo(() => serviceDocumentTypes(type), [type]);
  const upload = async (event) => {
    const file = event.target.files?.[0]; if (!file) return;
    setUploading(true); setError('');
    try { const response = await uploadOperationsDocumentApi(file, { type: documentTypes.includes(documentType) ? documentType : documentTypes[0], title: file.name, expiryDate: documentExpiry }); set('documents', [...form.documents, response.data]); }
    catch (requestError) { setError(requestError.message || 'Unable to upload document.'); }
    finally { setUploading(false); event.target.value = ''; }
  };
  const submit = (event) => {
    event.preventDefault();
    const payload = { ...form, updatedAt: service?.updatedAt };
    payload.hotelDetails.rooms = numberValue(payload.hotelDetails.rooms); payload.hotelDetails.nights = numberValue(payload.hotelDetails.nights);
    payload.transportDetails.capacity = numberValue(payload.transportDetails.capacity);
    payload.activityDetails.travelerCount = numberValue(payload.activityDetails.travelerCount); payload.activityDetails.dayNumber = numberValue(payload.activityDetails.dayNumber);
    onSave(payload);
  };

  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/65 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-200 bg-white p-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Trip execution</p><h2 className="mt-1 text-lg font-semibold text-slate-950">{title}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Close"><X size={18}/></button></header>
    <div className="grid gap-4 p-5 sm:grid-cols-2">
      {!service && <Field label="Service type"><select value={type} onChange={(event) => set('serviceType', event.target.value)} className={inputClass}>{['HOTEL','TRANSPORT','ACTIVITY','GUIDE'].map((value) => <option key={value}>{value}</option>)}</select></Field>}
      <Field label="Service title" wide><Text required value={form.title} onChange={(value) => set('title', value)} placeholder="A clear operational label"/></Field>
      <label className="flex items-center gap-2 text-sm font-medium text-slate-700 sm:col-span-2"><input type="checkbox" checked={form.required} onChange={(event) => set('required', event.target.checked)} className="h-4 w-4 rounded border-slate-300 text-emerald-600"/>Required for execution readiness</label>
      {type === 'HOTEL' && <><Field label="Hotel name"><Text value={form.hotelDetails.hotelName} onChange={(value) => setNested('hotelDetails','hotelName',value)}/></Field><Field label="City"><Text value={form.hotelDetails.city} onChange={(value) => setNested('hotelDetails','city',value)}/></Field><Field label="Check-in"><Text type="date" value={form.hotelDetails.checkIn} onChange={(value) => setNested('hotelDetails','checkIn',value)}/></Field><Field label="Check-out"><Text type="date" value={form.hotelDetails.checkOut} onChange={(value) => setNested('hotelDetails','checkOut',value)}/></Field><Field label="Room type"><Text value={form.hotelDetails.roomType} onChange={(value) => setNested('hotelDetails','roomType',value)}/></Field><Field label="Rooms"><Text type="number" min="0" value={form.hotelDetails.rooms} onChange={(value) => setNested('hotelDetails','rooms',value)}/></Field><Field label="Occupancy"><Text value={form.hotelDetails.occupancy} onChange={(value) => setNested('hotelDetails','occupancy',value)}/></Field><Field label="Meal plan"><Text value={form.hotelDetails.mealPlan} onChange={(value) => setNested('hotelDetails','mealPlan',value)}/></Field><Field label="Address" wide><Text value={form.hotelDetails.address} onChange={(value) => setNested('hotelDetails','address',value)}/></Field></>}
      {type === 'TRANSPORT' && <><Field label="Mode"><Text value={form.transportDetails.mode} onChange={(value) => setNested('transportDetails','mode',value)} placeholder="Road, flight, rail…"/></Field><Field label="Vehicle type"><Text value={form.transportDetails.vehicleType} onChange={(value) => setNested('transportDetails','vehicleType',value)}/></Field><Field label="From"><Text value={form.transportDetails.route.from} onChange={(value) => setRoute('from',value)}/></Field><Field label="To"><Text value={form.transportDetails.route.to} onChange={(value) => setRoute('to',value)}/></Field><Field label="Pickup point"><Text value={form.transportDetails.route.pickupPoint} onChange={(value) => setRoute('pickupPoint',value)}/></Field><Field label="Drop point"><Text value={form.transportDetails.route.dropPoint} onChange={(value) => setRoute('dropPoint',value)}/></Field><Field label="Departure date"><Text type="date" value={form.transportDetails.departureDate} onChange={(value) => setNested('transportDetails','departureDate',value)}/></Field><Field label="Departure time"><Text type="time" value={form.transportDetails.departureTime} onChange={(value) => setNested('transportDetails','departureTime',value)}/></Field><Field label="Vehicle number"><Text value={form.transportDetails.vehicleNumber} onChange={(value) => setNested('transportDetails','vehicleNumber',value)}/></Field><Field label="Capacity"><Text type="number" min="0" value={form.transportDetails.capacity} onChange={(value) => setNested('transportDetails','capacity',value)}/></Field></>}
      {type === 'ACTIVITY' && <><Field label="Activity"><Text value={form.activityDetails.activityName} onChange={(value) => setNested('activityDetails','activityName',value)}/></Field><Field label="Location"><Text value={form.activityDetails.location} onChange={(value) => setNested('activityDetails','location',value)}/></Field><Field label="Date"><Text type="date" value={form.activityDetails.date} onChange={(value) => setNested('activityDetails','date',value)}/></Field><Field label="Day number"><Text type="number" min="1" value={form.activityDetails.dayNumber} onChange={(value) => setNested('activityDetails','dayNumber',value)}/></Field><Field label="Start time"><Text type="time" value={form.activityDetails.startTime} onChange={(value) => setNested('activityDetails','startTime',value)}/></Field><Field label="Travelers"><Text type="number" min="0" value={form.activityDetails.travelerCount} onChange={(value) => setNested('activityDetails','travelerCount',value)}/></Field><Field label="Meeting point" wide><Text value={form.activityDetails.meetingPoint} onChange={(value) => setNested('activityDetails','meetingPoint',value)}/></Field></>}
      {type === 'GUIDE' && <><Field label="Guide name"><Text value={form.guideDetails.guideName} onChange={(value) => setNested('guideDetails','guideName',value)}/></Field><Field label="Phone"><Text value={form.guideDetails.phone} onChange={(value) => setNested('guideDetails','phone',value)}/></Field><Field label="Date"><Text type="date" value={form.guideDetails.date} onChange={(value) => setNested('guideDetails','date',value)}/></Field><Field label="Language"><Text value={form.guideDetails.language} onChange={(value) => setNested('guideDetails','language',value)}/></Field><Field label="Location"><Text value={form.guideDetails.location} onChange={(value) => setNested('guideDetails','location',value)}/></Field><Field label="Meeting point"><Text value={form.guideDetails.meetingPoint} onChange={(value) => setNested('guideDetails','meetingPoint',value)}/></Field></>}
      <Field label="Booking / confirmation reference"><Text value={form.bookingReference} onChange={(value) => set('bookingReference',value)}/></Field>
      <Field label="Internal notes" wide><textarea rows="4" value={form.internalNotes} onChange={(event) => set('internalNotes',event.target.value)} className={inputClass}/></Field>
      <div className="sm:col-span-2"><p className="text-sm font-medium text-slate-700">Internal documents</p><div className="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select value={documentType} onChange={(event) => setDocumentType(event.target.value)} className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm">{documentTypes.map((value) => <option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select><input type="date" value={documentExpiry} onChange={(event) => setDocumentExpiry(event.target.value)} aria-label="Document expiry date" className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"/><label className="inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"><FileUp size={16}/>{uploading ? 'Uploading…' : 'Upload'}<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="sr-only" disabled={uploading} onChange={upload}/></label></div><p className="mt-2 text-xs text-slate-500">{form.documents.length} document{form.documents.length === 1 ? '' : 's'} attached. Files remain internal to Operations.</p></div>
      {error && <p className="sm:col-span-2 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}
    </div>
    <footer className="sticky bottom-0 flex justify-end gap-2 border-t border-slate-200 bg-white p-4"><button type="button" onClick={onClose} className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700">Cancel</button><button type="submit" disabled={busy || uploading} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy && <Loader2 size={15} className="animate-spin"/>}{service ? 'Save changes' : 'Add service'}</button></footer>
  </form></div>;
}
