import { useCallback, useEffect, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Loader2, MessageSquarePlus, MessagesSquare } from 'lucide-react';
import { createOperationalCommunicationApi, getOperationalCommunicationsApi, getOperationalTripIncidentsApi, getOperationalTripTasksApi } from '../../../../../services/api.js';
import CommunicationFormModal from '../../components/CommunicationFormModal.jsx';
import OperationsStatusBadge from '../../components/OperationsStatusBadge.jsx';
import { formatOperationsDate } from '../../helpers/operationsFormatters.js';

export default function TripCommunicationsPanel({ operationId, trip }) {
  const [response, setResponse] = useState(null); const [relations, setRelations] = useState({ tasks: [], incidents: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [communications, tasks, incidents] = await Promise.all([getOperationalCommunicationsApi(operationId), getOperationalTripTasksApi(operationId), getOperationalTripIncidentsApi(operationId)]); setResponse(communications); setRelations({ tasks: tasks.data || [], incidents: incidents.data || [] }); } catch (requestError) { setError(requestError.message || 'Unable to load customer updates.'); } finally { setLoading(false); } }, [operationId]);
  useEffect(() => { void load(); }, [load]);
  const save = async (payload) => { await createOperationalCommunicationApi(operationId, payload); await load(); };
  if (loading && !response) return <div className="flex min-h-52 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 animate-spin" size={17}/>Loading communication history…</div>;
  return <section><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Factual history</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Customer Updates</h2><p className="mt-1 text-sm text-slate-500">{response?.summary?.count || 0} recorded communications. Logging does not send a message.</p></div><button onClick={() => setOpen(true)} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white"><MessageSquarePlus size={15}/>Log Customer Update</button></div>
    {error && <p role="alert" className="mt-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    {(response?.data || []).length === 0 ? <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><MessagesSquare className="mx-auto text-slate-300" size={32}/><h3 className="mt-3 font-semibold text-slate-900">No customer updates recorded.</h3><p className="mt-1 text-sm text-slate-500">Record calls, messages, and in-person updates after they occur.</p></div> : <div className="mt-5 space-y-3">{response.data.map((entry) => { const Icon = entry.direction === 'INBOUND' ? ArrowDownLeft : ArrowUpRight; return <article key={entry._id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${entry.direction === 'INBOUND' ? 'bg-sky-100 text-sky-700' : 'bg-emerald-100 text-emerald-700'}`}><Icon size={17}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><OperationsStatusBadge value={entry.direction}/><OperationsStatusBadge value={entry.channel}/><span className="text-xs text-slate-400">{formatOperationsDate(entry.occurredAt)}</span></div><h3 className="mt-2 font-semibold text-slate-900">{entry.summary}</h3>{entry.details && <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{entry.details}</p>}<p className="mt-2 text-xs text-slate-500">{entry.communicationType.replaceAll('_',' ')} · {entry.bookingId?.bookingId ? `${entry.bookingId.bookingId} / ${entry.bookingId.customer?.name}` : 'Whole departure'} · logged by {entry.loggedBy?.name || 'Staff'}</p></div></div></article>; })}</div>}
    {open && <CommunicationFormModal bookings={trip.bookings} services={trip.services} incidents={relations.incidents} tasks={relations.tasks} onClose={() => setOpen(false)} onSave={save}/>}
  </section>;
}
