import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, ListChecks, Loader2, LockKeyhole, Pencil, Play, Plus, RotateCcw, Sparkles } from 'lucide-react';
import {
  blockOperationalTaskApi, completeOperationalTaskApi, createOperationalTaskApi, getOperationalTripTasksApi,
  initializeOperationalChecklistApi, reopenOperationalTaskApi, startOperationalTaskApi, updateOperationalTaskApi
} from '../../../../../services/api.js';
import OperationsActionDialog from '../../components/OperationsActionDialog.jsx';
import OperationsStatusBadge from '../../components/OperationsStatusBadge.jsx';
import TaskFormModal from '../../components/TaskFormModal.jsx';
import { formatOperationsDate } from '../../helpers/operationsFormatters.js';

const labels = { PRE_TRIP: 'Pre-trip', DURING_TRIP: 'During trip', GENERAL: 'General' };
export default function TripTasksPanel({ operationId, trip, coordinators }) {
  const [response, setResponse] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [dialog, setDialog] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setResponse(await getOperationalTripTasksApi(operationId)); } catch (requestError) { setError(requestError.message || 'Unable to load journey tasks.'); } finally { setLoading(false); } }, [operationId]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (key, action) => { setBusy(key); setError(''); try { await action(); await load(); } catch (requestError) { setError(requestError.message || 'Unable to update the task.'); throw requestError; } finally { setBusy(''); } };
  const groups = useMemo(() => Object.fromEntries(['PRE_TRIP','DURING_TRIP','GENERAL'].map((category) => [category, (response?.data || []).filter((task) => task.category === category).sort((a,b) => (a.status === 'COMPLETED') - (b.status === 'COMPLETED') || String(a.dueAt || '9999').localeCompare(String(b.dueAt || '9999')))])), [response]);
  const summary = response?.summary || trip.taskSummary || { total: 0, completed: 0, open: 0, overdue: 0, blocked: 0 };
  if (loading && !response) return <div className="flex min-h-52 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 animate-spin" size={17}/>Loading checklist…</div>;
  return <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Team coordination</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Checklist &amp; Tasks</h2><p className="mt-1 text-sm text-slate-500">{summary.completed}/{summary.total} completed · {summary.open} open · {summary.overdue} overdue · {summary.blocked} blocked</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy === 'initialize'} onClick={() => mutate('initialize', () => initializeOperationalChecklistApi(operationId))} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><Sparkles size={15}/>Initialize Standard Checklist</button><button type="button" onClick={() => setDialog({ type: 'create' })} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-3 text-sm font-semibold text-white"><Plus size={15}/>Add Task</button></div></div>
    <div className="h-2 overflow-hidden rounded-full bg-slate-100" aria-label={`${summary.completed} of ${summary.total} tasks complete`}><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${summary.total ? Math.round(summary.completed / summary.total * 100) : 0}%` }}/></div>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    {(response?.data || []).length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><ListChecks className="mx-auto text-slate-300" size={32}/><h3 className="mt-3 font-semibold text-slate-900">No journey tasks yet.</h3><p className="mt-1 text-sm text-slate-500">Initialize the compact standard checklist or add a specific human follow-up.</p></div> : <div className="space-y-5">{Object.entries(groups).filter(([, tasks]) => tasks.length).map(([category, tasks]) => <div key={category}><h3 className="mb-2 text-sm font-semibold text-slate-800">{labels[category]}</h3><div className="grid gap-2">{tasks.map((task) => <article key={task._id} className={`rounded-xl border bg-white p-4 ${task.dueState === 'OVERDUE' ? 'border-rose-200' : 'border-slate-200'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold text-slate-900">{task.title}</h4><OperationsStatusBadge value={task.priority}/><OperationsStatusBadge value={task.status}/></div>{task.description && <p className="mt-1 text-sm text-slate-600">{task.description}</p>}<p className={`mt-2 text-xs ${task.dueState === 'OVERDUE' ? 'font-semibold text-rose-700' : 'text-slate-500'}`}>Due {formatOperationsDate(task.dueAt)} · {task.assignedTo?.name || 'Unassigned'}{task.blockedReason ? ` · Blocked: ${task.blockedReason}` : ''}</p></div><div className="flex shrink-0 flex-wrap gap-1.5">{task.status === 'TODO' && <button disabled={busy === task._id} onClick={() => mutate(task._id, () => startOperationalTaskApi(operationId, task._id))} className="inline-flex min-h-8 items-center gap-1 rounded-md border border-slate-200 px-2 text-xs font-semibold"><Play size={12}/>Start</button>}{['TODO','IN_PROGRESS','BLOCKED'].includes(task.status) && <button disabled={busy === task._id} onClick={() => mutate(task._id, () => completeOperationalTaskApi(operationId, task._id))} className="inline-flex min-h-8 items-center gap-1 rounded-md bg-emerald-600 px-2 text-xs font-semibold text-white"><CheckCircle2 size={12}/>Complete</button>}{['TODO','IN_PROGRESS'].includes(task.status) && <button onClick={() => setDialog({ type: 'block', task })} className="inline-flex min-h-8 items-center gap-1 rounded-md border border-amber-200 px-2 text-xs font-semibold text-amber-800"><LockKeyhole size={12}/>Block</button>}{task.status === 'COMPLETED' && <button onClick={() => setDialog({ type: 'reopen', task })} className="inline-flex min-h-8 items-center gap-1 rounded-md border border-slate-200 px-2 text-xs font-semibold"><RotateCcw size={12}/>Reopen</button>}{task.status !== 'CANCELLED' && <button onClick={() => setDialog({ type: 'edit', task })} aria-label={`Edit ${task.title}`} className="flex h-8 w-8 items-center justify-center rounded-md border border-slate-200"><Pencil size={13}/></button>}</div></div></article>)}</div></div>)}</div>}
    {dialog?.type === 'create' && <TaskFormModal coordinators={coordinators} services={trip.services} bookings={trip.bookings} onClose={() => setDialog(null)} onSave={(payload) => mutate('create', () => createOperationalTaskApi(operationId, payload))}/>}
    {dialog?.type === 'edit' && <TaskFormModal initial={dialog.task} coordinators={coordinators} services={trip.services} bookings={trip.bookings} onClose={() => setDialog(null)} onSave={(payload) => mutate(dialog.task._id, () => updateOperationalTaskApi(operationId, dialog.task._id, payload))}/>}
    {dialog?.type === 'block' && <OperationsActionDialog title="Block task" description={dialog.task.title} label="Blocked reason" placeholder="What is preventing progress?" confirmLabel="Block task" onClose={() => setDialog(null)} onConfirm={(reason) => mutate(dialog.task._id, () => blockOperationalTaskApi(operationId, dialog.task._id, reason))}/>}
    {dialog?.type === 'reopen' && <OperationsActionDialog title="Reopen task" description={dialog.task.title} label="Reason" placeholder="Why does this require more work?" confirmLabel="Reopen" onClose={() => setDialog(null)} onConfirm={(reason) => mutate(dialog.task._id, () => reopenOperationalTaskApi(operationId, dialog.task._id, reason))}/>}
  </section>;
}
