import { useCallback, useEffect, useState } from 'react';
import { Loader2, Search, X } from 'lucide-react';
import { getOperationsVendorsApi } from '../../../../../services/api.js';
import OperationsStatusBadge from '../../components/OperationsStatusBadge.jsx';

export default function VendorAssignmentModal({ service, driver = false, busy, onClose, onAssign, onOneOff }) {
  const [vendors, setVendors] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [oneOff, setOneOff] = useState({ name: '', phone: '', licenseNumber: '' });
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await getOperationsVendorsApi({ type: driver ? 'DRIVER' : service.serviceType, status: 'ACTIVE', search, limit: 20, sort: 'name' }); setVendors(response.data || []); } catch (requestError) { setError(requestError.message || 'Unable to load Vendors.'); } finally { setLoading(false); } }, [driver, search, service.serviceType]);
  useEffect(() => { const timer = setTimeout(() => { void load(); }, 200); return () => clearTimeout(timer); }, [load]);
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/65 p-4" role="dialog" aria-modal="true"><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-200 bg-white p-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">{driver ? 'Driver assignment' : 'Vendor assignment'}</p><h2 className="mt-1 font-semibold text-slate-950">{service.title}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></header><div className="space-y-4 p-5"><label className="relative block"><Search className="absolute left-3 top-3 text-slate-400" size={15}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search active ${driver ? 'drivers' : 'vendors'}…`} className="min-h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-emerald-500"/></label>{error && <p className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{loading ? <p className="flex items-center justify-center py-8 text-sm text-slate-500"><Loader2 className="mr-2 animate-spin" size={17}/>Loading directory…</p> : vendors.length ? <div className="divide-y divide-slate-100 rounded-lg border border-slate-200">{vendors.map((vendor) => <div key={vendor._id} className="flex items-center justify-between gap-3 p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{vendor.name}</p><p className="mt-1 text-xs text-slate-500">{vendor.vendorCode} · {vendor.location?.city || 'Location not recorded'} · {vendor.contact?.phone || vendor.contact?.email || 'Contact not recorded'}</p></div><button type="button" disabled={busy} onClick={() => onAssign(vendor._id)} className="min-h-9 shrink-0 rounded-lg bg-slate-950 px-3 text-xs font-semibold text-white disabled:opacity-50">Assign</button></div>)}</div> : <p className="rounded-lg border border-dashed border-slate-300 py-7 text-center text-sm text-slate-500">No compatible active Vendors found.</p>}
      {driver && <div className="border-t border-slate-200 pt-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-900">One-off driver</h3><OperationsStatusBadge value="MANUAL"/></div><p className="mt-1 text-xs text-slate-500">Use when this driver should not be added to the reusable Vendor directory.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={oneOff.name} onChange={(event) => setOneOff((value) => ({ ...value, name: event.target.value }))} placeholder="Driver name" className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"/><input value={oneOff.phone} onChange={(event) => setOneOff((value) => ({ ...value, phone: event.target.value }))} placeholder="Phone" className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"/><input value={oneOff.licenseNumber} onChange={(event) => setOneOff((value) => ({ ...value, licenseNumber: event.target.value }))} placeholder="License number (optional)" className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm sm:col-span-2"/></div><button type="button" disabled={busy || !oneOff.name.trim() || !oneOff.phone.trim()} onClick={() => onOneOff(oneOff)} className="mt-3 min-h-10 rounded-lg border border-slate-300 px-4 text-sm font-semibold text-slate-800 disabled:opacity-50">Assign one-off driver</button></div>}
    </div></section></div>;
}
