import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { AlertCircle, RefreshCw, Users } from 'lucide-react';
import { getMarketingLeadAnalyticsApi, getMarketingLeadAnalyticsOptionsApi } from '../../../../services/api.js';
import { getApiErrorMessage } from '../../../../services/apiConfig.js';
import { formatCount, formatCurrency, formatDuration, formatPercent, titleCase } from './leadAnalyticsHelpers.js';

const initialFilters = { range: '30d', campaignId: '', source: '', medium: '', destination: '', leadType: '', from: '', to: '' };
const control = 'min-h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10';

const Metric = ({ label, value, hint }) => <div className="border-l-2 border-emerald-600 bg-white px-4 py-3"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{hint}</p></div>;
const Section = ({ title, subtitle, children }) => <section className="min-w-0 rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">{title}</h2>{subtitle && <p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div>{children}</section>;
const Empty = () => <div className="px-5 py-12 text-center"><Users className="mx-auto text-slate-300" size={26}/><p className="mt-3 text-sm font-semibold text-slate-800">No Leads were acquired for this selection.</p><p className="mt-1 text-xs text-slate-500">Adjust the cohort filters or choose a wider date range.</p></div>;
const Loading = () => <div className="space-y-3" aria-label="Loading analytics"><div className="h-20 animate-pulse rounded-xl bg-slate-100"/><div className="h-56 animate-pulse rounded-xl bg-slate-100"/><div className="h-72 animate-pulse rounded-xl bg-slate-100"/></div>;
const Table = ({ columns, rows, empty = 'No data for this selection.' }) => <div className="max-w-full overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold text-slate-500"><tr>{columns.map((column) => <th key={column.key} className="px-4 py-3">{column.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.length ? rows.map((row, index) => <tr key={row.key || row.referenceId || index} className="hover:bg-slate-50/70">{columns.map((column) => <td key={column.key} className="px-4 py-3 text-slate-700">{column.render ? column.render(row) : row[column.key]}</td>)}</tr>) : <tr><td colSpan={columns.length} className="px-4 py-10 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div>;

const Funnel = ({ rows }) => <div className="grid gap-2 p-5 md:grid-cols-6">{rows.map((item, index) => <div key={item.stage} className="relative rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-medium text-slate-500">{item.stage}</p><p className="mt-2 text-xl font-semibold text-slate-950">{formatCount(item.count)}</p><p className="mt-1 text-xs text-emerald-700">{formatPercent(item.cohortRate)} of cohort</p>{index < rows.length - 1 && <span aria-hidden="true" className="absolute -right-2 top-1/2 z-10 hidden -translate-y-1/2 bg-white px-0.5 text-slate-300 md:block">›</span>}</div>)}</div>;
const trendLabel = (value) => {
  const parts = String(value || '').split('-').map(Number);
  if (parts.length === 2) return new Intl.DateTimeFormat('en-IN', { month: 'short', year: 'numeric', timeZone: 'Asia/Kolkata' }).format(new Date(Date.UTC(parts[0], parts[1] - 1, 1)));
  if (parts.length === 3) return new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', timeZone: 'Asia/Kolkata' }).format(new Date(Date.UTC(parts[0], parts[1] - 1, parts[2])));
  return value;
};
const Trend = ({ rows }) => {
  const max = Math.max(1, ...rows.map((row) => row.leads));
  return <div className="space-y-2 p-5">{rows.map((row) => <div key={row.date} className="grid grid-cols-[88px_1fr_auto] items-center gap-3 text-xs"><span className="text-slate-500">{trendLabel(row.date)}</span><div className="h-2 overflow-hidden rounded-full bg-slate-100" aria-hidden="true"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${Math.max(3, (row.leads / max) * 100)}%` }}/></div><span className="min-w-28 text-right text-slate-600">{row.leads} Leads · {row.bookings} Bookings · {row.paying} Paying</span></div>)}</div>;
};

export default function MarketingLeadAnalyticsWorkspace() {
  const [searchParams] = useSearchParams();
  const initial = { ...initialFilters, campaignId: searchParams.get('campaignId') || '' };
  const [filters, setFilters] = useState(initial); const [applied, setApplied] = useState(initial);
  const [options, setOptions] = useState({ campaigns: [], sources: [], mediums: [], destinations: [], leadTypes: [] });
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const requestId = useRef(0);
  const load = useCallback(async () => {
    const current = ++requestId.current; setLoading(true); setError('');
    try { const result = await getMarketingLeadAnalyticsApi(applied); if (current === requestId.current) setData(result); }
    catch (err) { if (current === requestId.current) setError(getApiErrorMessage(err, 'Unable to load lead analytics.')); }
    finally { if (current === requestId.current) setLoading(false); }
  }, [applied]);
  useEffect(() => { getMarketingLeadAnalyticsOptionsApi().then((result) => setOptions(result.options || {})).catch(() => {}); }, []);
  useEffect(() => { load(); }, [load]);
  const summary = data?.summary || {}; const currency = summary.currency || 'INR';
  const selectedCampaignPerformance = applied.campaignId && applied.campaignId !== 'unattributed' ? data?.campaignBreakdown?.find((row) => row.campaignId === applied.campaignId) : null;
  const apply = (event) => { event.preventDefault(); setApplied(filters); };
  const select = (key, label, values, render = titleCase) => <label className="grid gap-1 text-xs font-medium text-slate-600"><span>{label}</span><select value={filters[key]} onChange={(event) => setFilters((value) => ({ ...value, [key]: event.target.value }))} className={control}><option value="">All {label}</option>{values.map((value) => <option key={value._id || value} value={value._id || value}>{render(value)}</option>)}</select></label>;
  const commercialColumns = [
    { key: 'campaign', label: 'Campaign', render: (row) => <div><p className="font-medium text-slate-900">{row.campaign}</p><p className="text-xs text-slate-400">{row.code || `${row.source} / ${row.medium}`}</p></div> },
    { key: 'spend', label: 'Actual Spend', render: (row) => row.spend > 0 ? formatCurrency(row.spend) : 'Not recorded' },
    { key: 'leads', label: 'Leads' }, { key: 'qualified', label: 'Qualified' }, { key: 'bookings', label: 'Bookings' }, { key: 'paying', label: 'Paying' },
    { key: 'leadToPaidRate', label: 'Lead to Paid', render: (row) => formatPercent(row.leadToPaidRate) },
    { key: 'paidRevenue', label: 'Paid Revenue', render: (row) => formatCurrency(row.paidRevenue, currency) },
    { key: 'customerAcquisitionCost', label: 'CAC', render: (row) => row.customerAcquisitionCost == null ? 'Spend not recorded' : formatCurrency(row.customerAcquisitionCost) },
    { key: 'view', label: '', render: (row) => row.campaignId ? <button type="button" onClick={() => { const next = { ...applied, campaignId: row.campaignId }; setFilters(next); setApplied(next); }} className="font-semibold text-emerald-700 hover:text-emerald-900">View</button> : null }
  ];

  return <div className="space-y-6">
    <header className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-emerald-700">Marketing</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Lead & Conversion Analytics</h1><p className="mt-2 text-sm text-slate-600">Understand where potential customers come from and how many progress from Lead to paid booking.</p></div><button type="button" onClick={load} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/>Refresh</button></header>
    <form onSubmit={apply} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-3 xl:grid-cols-7">
      <label className="grid gap-1 text-xs font-medium text-slate-600"><span>Date Range</span><select value={filters.range} onChange={(event) => setFilters((value) => ({ ...value, range: event.target.value }))} className={control}><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="90d">Last 90 Days</option><option value="all">All Time</option><option value="custom">Custom</option></select></label>
      {select('campaignId', 'Campaigns', [{ _id: 'unattributed', name: 'Direct / Unattributed' }, ...(options.campaigns || [])], (item) => item.name)}
      {select('source', 'Sources', options.sources || [])}{select('medium', 'Mediums', options.mediums || [])}{select('destination', 'Destinations', options.destinations || [])}{select('leadType', 'Lead Types', options.leadTypes || [])}
      <button className="mt-auto min-h-10 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white hover:bg-slate-800">Apply</button>
      {filters.range === 'custom' && <><label className="grid gap-1 text-xs font-medium text-slate-600"><span>From</span><input required type="date" value={filters.from} onChange={(event) => setFilters((value) => ({ ...value, from: event.target.value }))} className={control}/></label><label className="grid gap-1 text-xs font-medium text-slate-600"><span>To</span><input required type="date" value={filters.to} onChange={(event) => setFilters((value) => ({ ...value, to: event.target.value }))} className={control}/></label></>}
    </form>
    <p className="text-xs text-slate-500">Conversion metrics are cohort-based. The selected date range determines when Leads were acquired. Later bookings and payments are credited back to that Lead cohort.</p>
    {error ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-6 text-center"><AlertCircle className="mx-auto text-rose-600"/><p className="mt-3 text-sm font-semibold text-rose-900">{error}</p><button onClick={load} className="mt-4 rounded-lg bg-rose-700 px-4 py-2 text-sm font-semibold text-white">Retry</button></div> : loading && !data ? <Loading/> : summary.potentialLeads === 0 ? <Section title="Lead acquisition"><Empty/></Section> : <>
      <section className="grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 lg:grid-cols-4"><Metric label="Potential Customers" value={formatCount(summary.potentialLeads)} hint="Persisted Leads in cohort"/><Metric label="Contacted" value={formatCount(summary.contactedLeads)} hint="Authoritative contact evidence"/><Metric label="Qualified" value={formatCount(summary.qualifiedLeads)} hint="Qualified or progressed"/><Metric label="Paying Customers" value={formatCount(summary.payingCustomers)} hint="Real payment received"/><Metric label="Bookings" value={formatCount(summary.bookingLeads)} hint="Exact Booking.leadId links"/><Metric label="Lead to Booking" value={formatPercent(summary.leadToBookingRate)} hint="Of original Lead cohort"/><Metric label="Lead to Paid" value={formatPercent(summary.leadToPaidRate)} hint="Primary customer conversion"/><Metric label="Paid Revenue" value={formatCurrency(summary.paidRevenue, currency)} hint="Actual amount collected"/></section>
      <section className="grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Booking Value" value={formatCurrency(summary.bookingValue, currency)} hint="Attributed booking final amounts"/><Metric label="Avg First Contact" value={formatDuration(summary.averageFirstContactMinutes, 'minutes')} hint="Created to first contact"/><Metric label="Avg Lead to Booking" value={formatDuration(summary.averageLeadToBookingHours, 'hours')} hint="Created to earliest booking"/><Metric label="Attribution Coverage" value={formatPercent(summary.attributionCoverage)} hint="Meaningful non-direct first touch"/></section>
      {selectedCampaignPerformance && <section className="grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-3"><Metric label="Cost per Lead" value={selectedCampaignPerformance.costPerLead == null ? 'Spend not recorded' : formatCurrency(selectedCampaignPerformance.costPerLead)} hint="Actual Spend divided by Leads"/><Metric label="Customer Acquisition Cost" value={selectedCampaignPerformance.customerAcquisitionCost == null ? 'Spend not recorded' : formatCurrency(selectedCampaignPerformance.customerAcquisitionCost)} hint="Actual Spend divided by paying customers"/><Metric label="Paid ROAS" value={selectedCampaignPerformance.paidRoas == null ? 'Spend not recorded' : `${selectedCampaignPerformance.paidRoas.toFixed(2)}x`} hint="Paid Revenue divided by Actual Spend"/></section>}
      {summary.currencyBreakdown?.some((item) => item.currency !== 'INR') && <Section title="Commercial Totals by Currency" subtitle="Currencies are kept separate and are never summed as if they were comparable."><Table columns={[{ key: 'currency', label: 'Currency' }, { key: 'bookingValue', label: 'Booking Value', render: (row) => formatCurrency(row.bookingValue, row.currency) }, { key: 'paidRevenue', label: 'Paid Revenue', render: (row) => formatCurrency(row.paidRevenue, row.currency) }]} rows={summary.currencyBreakdown}/></Section>}
      <Section title="Lead Conversion Funnel" subtitle="Every stage counts unique Leads and uses the original cohort as denominator."><Funnel rows={data.funnel || []}/></Section>
      <Section title="Lead Acquisition Trend" subtitle="Bookings and paying customers are credited to the date their Lead was acquired."><Trend rows={data.trend || []}/></Section>
      <Section title="Campaign Performance" subtitle="Actual spend is entered manually. Paid revenue uses Booking.pricing.amountPaid."><Table columns={commercialColumns} rows={data.campaignBreakdown || []}/></Section>
      <div className="grid gap-6 xl:grid-cols-2"><Section title="Source Performance"><Table columns={[{ key: 'source', label: 'Source' }, { key: 'medium', label: 'Medium' }, { key: 'leads', label: 'Leads' }, { key: 'bookings', label: 'Bookings' }, { key: 'paying', label: 'Paying' }, { key: 'leadToPaidRate', label: 'Conversion', render: (row) => formatPercent(row.leadToPaidRate) }, { key: 'paidRevenue', label: 'Paid Revenue', render: (row) => formatCurrency(row.paidRevenue, currency) }]} rows={data.sourceBreakdown || []}/></Section><Section title="Destination Performance"><Table columns={[{ key: 'destination', label: 'Destination' }, { key: 'leads', label: 'Leads' }, { key: 'bookings', label: 'Bookings' }, { key: 'paying', label: 'Paying' }, { key: 'leadToPaidRate', label: 'Conversion', render: (row) => formatPercent(row.leadToPaidRate) }, { key: 'paidRevenue', label: 'Paid Revenue', render: (row) => formatCurrency(row.paidRevenue, currency) }]} rows={data.destinationBreakdown || []}/></Section></div>
      <div className="grid gap-6 xl:grid-cols-2"><Section title="Lead Capture Points" subtitle="Where travelers submitted a Lead on the website."><Table columns={[{ key: 'capturePoint', label: 'Capture Point', render: (row) => titleCase(row.capturePoint) }, { key: 'leads', label: 'Leads' }, { key: 'bookings', label: 'Bookings' }, { key: 'paying', label: 'Paying' }]} rows={data.capturePointBreakdown || []}/></Section><Section title="Why Leads Are Lost"><Table columns={[{ key: 'reason', label: 'Lost Reason' }, { key: 'count', label: 'Leads' }]} rows={data.lostReasonBreakdown || []}/></Section></div>
      {Boolean(data.creativeBreakdown?.length || data.keywordBreakdown?.length) && <div className="grid gap-6 xl:grid-cols-2">{data.creativeBreakdown?.length > 0 && <Section title="Top Creatives"><Table columns={[{ key: 'creative', label: 'Creative' }, { key: 'leads', label: 'Leads' }, { key: 'paying', label: 'Paying' }, { key: 'leadToPaidRate', label: 'Conversion', render: (row) => formatPercent(row.leadToPaidRate) }]} rows={data.creativeBreakdown}/></Section>}{data.keywordBreakdown?.length > 0 && <Section title="Top Keywords"><Table columns={[{ key: 'term', label: 'Keyword' }, { key: 'leads', label: 'Leads' }, { key: 'paying', label: 'Paying' }, { key: 'leadToPaidRate', label: 'Conversion', render: (row) => formatPercent(row.leadToPaidRate) }]} rows={data.keywordBreakdown}/></Section>}</div>}
      <Section title="Recent Lead Cohort" subtitle="Sanitized acquisition and outcome details. Contact information and private notes are excluded."><Table columns={[{ key: 'referenceId', label: 'Lead Ref', render: (row) => <span className="font-medium text-slate-900">{row.referenceId}</span> }, { key: 'acquiredAt', label: 'Acquired', render: (row) => new Date(row.acquiredAt).toLocaleDateString('en-IN') }, { key: 'destination', label: 'Destination' }, { key: 'source', label: 'Source / Medium', render: (row) => `${row.source} / ${row.medium}` }, { key: 'campaign', label: 'Campaign' }, { key: 'stage', label: 'Current Stage' }, { key: 'paymentState', label: 'Payment' }]} rows={data.recentLeads || []}/></Section>
    </>}
  </div>;
}
