import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Mail, Lock, Eye, EyeOff, Sparkles, ArrowRight, KeyRound, DollarSign, TrendingUp } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

const InfluencerLogin = () => {
  const [email, setEmail] = useState('influencer@wanderluxe.in');
  const [password, setPassword] = useState('influencer123');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const { user, influencerLogin, isAuthenticated } = useAuth();
  const navigate = useNavigate();

  // If already logged in as Influencer, redirect to /influencer
  useEffect(() => {
    if (isAuthenticated && (user?.role === 'influencer' || user?.email?.toLowerCase() === 'influencer@wanderluxe.in')) {
      navigate('/influencer', { replace: true });
    }
  }, [isAuthenticated, user, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!email || !password) {
      setError('Please enter both influencer email and password.');
      return;
    }

    setLoading(true);
    try {
      await influencerLogin(email, password);
      setLoading(false);
      navigate('/influencer', { replace: true });
    } catch (err) {
      setLoading(false);
      setError(err.message || 'Invalid Influencer Credentials.');
    }
  };

  const handleInfluencerQuickLogin = async () => {
    setLoading(true);
    try {
      await influencerLogin('influencer@wanderluxe.in', 'influencer123');
      setLoading(false);
      navigate('/influencer', { replace: true });
    } catch (err) {
      setLoading(false);
      setError('Influencer quick login failed.');
    }
  };

  return (
    <div className="min-h-screen pt-24 pb-16 flex items-center justify-center bg-brand-navy px-4 relative overflow-hidden">
      {/* Background Orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-brand-emerald opacity-10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-brand-teal opacity-10 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-4xl w-full bg-white/95 backdrop-blur-xl rounded-3xl shadow-2xl overflow-hidden border border-white/20 grid grid-cols-1 md:grid-cols-2 relative z-10">
        {/* Left Side: Influencer Branding */}
        <div className="relative hidden md:flex flex-col justify-between p-10 bg-gradient-to-b from-brand-navy via-brand-navy to-emerald-950 text-white border-r border-white/10">
          <div>
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brand-emerald/20 border border-brand-emerald/40 text-xs font-extrabold text-brand-emerald mb-6">
              <Sparkles size={16} /> Partner & Influencer Portal
            </div>
            <h2 className="text-3xl font-extrabold leading-tight mb-4 text-white">
              Monetize Your Travel Audience with WanderLuxe
            </h2>
            <p className="text-white/70 text-sm leading-relaxed font-medium">
              Generate custom coupon codes, track real-time bookings generated by your followers, and earn up to 10% commission on gross sales.
            </p>
          </div>

          <div className="pt-8 border-t border-white/10 space-y-3">
            <div className="flex items-center gap-3 text-xs font-bold text-brand-emerald">
              <TrendingUp size={18} /> Over ₹48.5k Earned by Top Creators
            </div>
            <div className="text-[11px] text-white/50 font-mono">
              Official Partner Email: influencer@wanderluxe.in
            </div>
          </div>
        </div>

        {/* Right Side: Login Form */}
        <div className="p-8 md:p-12 flex flex-col justify-center text-brand-navy">
          <div className="mb-6">
            <span className="text-xs font-extrabold text-brand-emerald uppercase tracking-wider block mb-1">
              Creator Login
            </span>
            <h1 className="text-2xl md:text-3xl font-extrabold text-brand-navy">Influencer Control Panel</h1>
            <p className="text-gray-500 text-xs mt-1">Sign in to manage custom coupons & track commission earnings</p>
          </div>

          {error && (
            <div className="mb-6 p-4 rounded-2xl bg-red-50 border border-red-200 text-red-600 text-xs font-bold">
              {error}
            </div>
          )}

          {/* 1-Click Quick Login */}
          <button
            type="button"
            onClick={handleInfluencerQuickLogin}
            className="mb-6 w-full py-3.5 px-4 bg-brand-navy text-white font-extrabold rounded-2xl hover:bg-brand-emerald transition-all flex items-center justify-center gap-2 text-xs shadow-lg shadow-brand-navy/20"
          >
            <KeyRound size={16} className="text-brand-emerald" />
            1-Click Influencer Login (influencer@wanderluxe.in)
          </button>

          <div className="relative flex py-2 items-center mb-6">
            <div className="flex-grow border-t border-gray-200"></div>
            <span className="flex-shrink mx-4 text-[10px] font-extrabold text-gray-400 uppercase tracking-widest">
              or enter partner details
            </span>
            <div className="flex-grow border-t border-gray-200"></div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-xs font-extrabold uppercase tracking-wider text-brand-navy mb-1.5">
                Influencer Email
              </label>
              <div className="relative">
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="influencer@wanderluxe.in"
                  className="w-full pl-11 pr-4 py-3 bg-brand-light border border-gray-200 rounded-2xl focus:outline-none focus:border-brand-emerald text-brand-navy text-xs font-bold"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-extrabold uppercase tracking-wider text-brand-navy mb-1.5">
                Password
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="influencer123"
                  className="w-full pl-11 pr-12 py-3 bg-brand-light border border-gray-200 rounded-2xl focus:outline-none focus:border-brand-emerald text-brand-navy text-xs font-bold"
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-brand-navy"
                >
                  {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                </button>
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-4 bg-brand-emerald text-white rounded-2xl font-extrabold text-sm hover:bg-brand-teal transition-all shadow-xl shadow-brand-emerald/30 flex items-center justify-center gap-2 mt-2"
            >
              {loading ? (
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <>
                  Access Influencer Dashboard <ArrowRight size={18} />
                </>
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default InfluencerLogin;
