import React from 'react';
import { Plus, Trash2 } from 'lucide-react';

const input = 'mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100';
const emptySection = () => ({ heading: '', subheading: '', body: '', imageUrl: '', imageAlt: '', ctaLabel: '', ctaUrl: '' });

const PageContentForm = ({ page, onChange }) => {
  const updateSection = (index, key, value) => onChange('sections', page.sections.map((section, current) => current === index ? { ...section, [key]: value } : section));
  const removeSection = (index) => onChange('sections', page.sections.filter((_, current) => current !== index));
  return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-950">Content</h2><p className="mt-1 text-xs text-slate-500">Preserves the existing intro text and ordered section structure.</p></div><button type="button" onClick={() => onChange('sections', [...page.sections, emptySection()])} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-700"><Plus size={14} />Add section</button></div><label className="mt-4 block text-sm font-medium text-slate-700">Intro content<textarea rows="7" value={page.content} onChange={(e) => onChange('content', e.target.value)} className={input} /></label><div className="mt-5 space-y-4">{page.sections.map((section, index) => <div key={index} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Section {index + 1}</p><button type="button" onClick={() => removeSection(index)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><Trash2 size={15} /></button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium text-slate-600">Heading<input value={section.heading} onChange={(e) => updateSection(index, 'heading', e.target.value)} className={input} /></label><label className="text-xs font-medium text-slate-600">Subheading<input value={section.subheading} onChange={(e) => updateSection(index, 'subheading', e.target.value)} className={input} /></label><label className="text-xs font-medium text-slate-600 sm:col-span-2">Body<textarea rows="5" value={section.body} onChange={(e) => updateSection(index, 'body', e.target.value)} className={input} /></label><label className="text-xs font-medium text-slate-600">Image URL<input type="url" value={section.imageUrl} onChange={(e) => updateSection(index, 'imageUrl', e.target.value)} className={input} /></label><label className="text-xs font-medium text-slate-600">Image alt text<input value={section.imageAlt} onChange={(e) => updateSection(index, 'imageAlt', e.target.value)} className={input} /></label><label className="text-xs font-medium text-slate-600">CTA label<input value={section.ctaLabel} onChange={(e) => updateSection(index, 'ctaLabel', e.target.value)} className={input} /></label><label className="text-xs font-medium text-slate-600">CTA URL<input value={section.ctaUrl} onChange={(e) => updateSection(index, 'ctaUrl', e.target.value)} className={input} /></label></div></div>)}</div></section>;
};

export default PageContentForm;

