import React from 'react';
import { ExternalLink, Pencil, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { formatPageDate } from '../pageHelpers.js';

const Status = ({ value }) => <span className={`rounded-full border px-2 py-0.5 text-[11px] font-semibold ${value === 'published' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-amber-200 bg-amber-50 text-amber-800'}`}>{value === 'published' ? 'Published' : 'Draft'}</span>;
const PagesTable = ({ pages, onDelete }) => <div className="hidden overflow-x-auto rounded-xl border border-slate-200 bg-white lg:block"><table className="w-full min-w-[880px] text-left"><thead className="border-b border-slate-200 bg-slate-50 text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500"><tr><th className="px-4 py-3">Page</th><th className="px-4 py-3">Slug</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">SEO</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{pages.map((page) => <tr key={page._id} className="hover:bg-slate-50/70"><td className="px-4 py-4"><p className="max-w-72 truncate text-sm font-semibold text-slate-900">{page.title}</p><p className="mt-1 text-xs text-slate-500">{page.category || 'General'} · {page.author || 'No author'}</p></td><td className="px-4 py-4 font-mono text-xs text-slate-600">/page/{page.slug}</td><td className="px-4 py-4"><Status value={page.status} /></td><td className="px-4 py-4 text-sm font-semibold text-slate-700">{page.seoHealthScore ?? 0}%</td><td className="px-4 py-4 text-xs text-slate-500">{formatPageDate(page.updatedAt)}</td><td className="px-4 py-4"><div className="flex gap-1"><Link to={`/staff/admin/pages/${page._id}/edit`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title="Edit"><Pencil size={15} /></Link>{page.status === 'published' && <a href={`/page/${page.slug}`} target="_blank" rel="noreferrer" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title="Open public page"><ExternalLink size={15} /></a>}<button type="button" onClick={() => onDelete(page)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" title="Delete"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>;

export default PagesTable;

