import { useState } from 'react';
import { FileUp, Loader2 } from 'lucide-react';
import { uploadOperationsDocumentApi } from '../../../../../services/api.js';

const vendorTypes = ['HOTEL', 'TRANSPORT', 'DRIVER', 'ACTIVITY', 'GUIDE'];
const rateTypes = ['CUSTOM', 'PER_ROOM_NIGHT', 'PER_NIGHT', 'PER_VEHICLE', 'PER_DAY', 'PER_PERSON', 'PER_ACTIVITY', 'FIXED'];
const inputClass = 'mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 text-sm text-slate-800 outline-none focus:border-emerald-500';
const initial = (vendor) => ({
  name: vendor?.name || '', types: vendor?.types || [], contact: { personName: vendor?.contact?.personName || '', phone: vendor?.contact?.phone || '', alternatePhone: vendor?.contact?.alternatePhone || '', whatsapp: vendor?.contact?.whatsapp || '', email: vendor?.contact?.email || '' },
  location: { address: vendor?.location?.address || '', city: vendor?.location?.city || '', state: vendor?.location?.state || '', country: vendor?.location?.country || 'India', pincode: vendor?.location?.pincode || '' },
  serviceAreas: (vendor?.serviceAreas || []).join(', '), commercialReference: { currency: vendor?.commercialReference?.currency || 'INR', rateType: vendor?.commercialReference?.rateType || 'CUSTOM', defaultRate: vendor?.commercialReference?.defaultRate ?? '', taxPercent: vendor?.commercialReference?.taxPercent ?? '', paymentTerms: vendor?.commercialReference?.paymentTerms || '', notes: vendor?.commercialReference?.notes || '' }, documents: vendor?.documents || [], notes: vendor?.notes || '', updatedAt: vendor?.updatedAt
});
const Section = ({ title, description, children }) => <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">{title}</h2>{description && <p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>}<div className="mt-4 grid gap-4 sm:grid-cols-2">{children}</div></section>;
const Field = ({ label, children, wide = false }) => <label className={`text-sm font-medium text-slate-700 ${wide ? 'sm:col-span-2' : ''}`}>{label}{children}</label>;

export default function VendorForm({ vendor, busy, error, onSubmit }) {
  const [form, setForm] = useState(() => initial(vendor)); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState(''); const [documentType, setDocumentType] = useState('AGREEMENT'); const [documentExpiry, setDocumentExpiry] = useState('');
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value })); const nested = (key, child, value) => setForm((current) => ({ ...current, [key]: { ...current[key], [child]: value } }));
  const toggleType = (type) => set('types', form.types.includes(type) ? form.types.filter((value) => value !== type) : [...form.types, type]);
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setUploadError(''); try { const response = await uploadOperationsDocumentApi(file, { type: documentType, title: file.name, expiryDate: documentExpiry }); set('documents', [...form.documents, response.data]); } catch (requestError) { setUploadError(requestError.message || 'Unable to upload document.'); } finally { setUploading(false); event.target.value = ''; } };
  const submit = (event) => { event.preventDefault(); onSubmit({ ...form, serviceAreas: form.serviceAreas.split(',').map((value) => value.trim()).filter(Boolean), commercialReference: { ...form.commercialReference, defaultRate: form.commercialReference.defaultRate === '' ? null : Number(form.commercialReference.defaultRate), taxPercent: form.commercialReference.taxPercent === '' ? null : Number(form.commercialReference.taxPercent) } }); };
  return <form onSubmit={submit} className="space-y-5"><Section title="Identity & capability" description="Types control which operational services can use this Vendor."><Field label="Vendor name" wide><input required value={form.name} onChange={(event) => set('name', event.target.value)} className={inputClass}/></Field><div className="sm:col-span-2"><p className="text-sm font-medium text-slate-700">Vendor types</p><div className="mt-2 flex flex-wrap gap-2">{vendorTypes.map((type) => <label key={type} className={`cursor-pointer rounded-lg border px-3 py-2 text-xs font-semibold ${form.types.includes(type) ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-slate-200 text-slate-600'}`}><input type="checkbox" checked={form.types.includes(type)} onChange={() => toggleType(type)} className="sr-only"/>{type}</label>)}</div></div></Section>
    <Section title="Contact" description="At least one phone, WhatsApp number, or email is required.">{[['Contact person','personName'],['Phone','phone'],['Alternate phone','alternatePhone'],['WhatsApp','whatsapp'],['Email','email']].map(([label,key]) => <Field key={key} label={label}><input type={key === 'email' ? 'email' : 'text'} value={form.contact[key]} onChange={(event) => nested('contact',key,event.target.value)} className={inputClass}/></Field>)}</Section>
    <Section title="Location & service areas"><Field label="Address" wide><textarea rows="3" value={form.location.address} onChange={(event) => nested('location','address',event.target.value)} className={inputClass}/></Field>{[['City','city'],['State','state'],['Country','country'],['Pincode','pincode']].map(([label,key]) => <Field key={key} label={label}><input value={form.location[key]} onChange={(event) => nested('location',key,event.target.value)} className={inputClass}/></Field>)}<Field label="Service areas" wide><input value={form.serviceAreas} onChange={(event) => set('serviceAreas',event.target.value)} placeholder="Delhi, Jaipur, Udaipur" className={inputClass}/><span className="mt-1 block text-xs font-normal text-slate-500">Comma-separated.</span></Field></Section>
    <Section title="Commercial reference" description="Reference-only terms for Operations; settlements are intentionally deferred."><Field label="Currency"><input value={form.commercialReference.currency} onChange={(event) => nested('commercialReference','currency',event.target.value)} className={inputClass}/></Field><Field label="Rate type"><select value={form.commercialReference.rateType} onChange={(event) => nested('commercialReference','rateType',event.target.value)} className={inputClass}>{rateTypes.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Default rate"><input type="number" min="0" value={form.commercialReference.defaultRate} onChange={(event) => nested('commercialReference','defaultRate',event.target.value)} className={inputClass}/></Field><Field label="Tax %"><input type="number" min="0" max="100" value={form.commercialReference.taxPercent} onChange={(event) => nested('commercialReference','taxPercent',event.target.value)} className={inputClass}/></Field><Field label="Payment terms" wide><textarea rows="3" value={form.commercialReference.paymentTerms} onChange={(event) => nested('commercialReference','paymentTerms',event.target.value)} className={inputClass}/></Field></Section>
    <Section title="Internal records"><Field label="Internal notes" wide><textarea rows="5" value={form.notes} onChange={(event) => set('notes',event.target.value)} className={inputClass}/></Field><div className="sm:col-span-2"><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select value={documentType} onChange={(event) => setDocumentType(event.target.value)} aria-label="Document type" className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm">{['AGREEMENT','RATE_CARD','LICENSE','REGISTRATION','INSURANCE','ID','OTHER'].map((value) => <option key={value}>{value.replaceAll('_',' ')}</option>)}</select><input type="date" value={documentExpiry} onChange={(event) => setDocumentExpiry(event.target.value)} aria-label="Document expiry date" className="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"/><label className="inline-flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><FileUp size={16}/>{uploading ? 'Uploading…' : 'Upload'}<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="sr-only" disabled={uploading} onChange={upload}/></label></div><p className="mt-2 text-xs text-slate-500">{form.documents.length} document{form.documents.length === 1 ? '' : 's'} attached.</p></div></Section>
    {(error || uploadError) && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error || uploadError}</p>}
    <div className="flex justify-end"><button type="submit" disabled={busy || uploading || !form.types.length} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-emerald-600 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy && <Loader2 size={16} className="animate-spin"/>}{vendor ? 'Save Vendor' : 'Create Vendor'}</button></div></form>;
}
