import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, ExternalLink, FileText, Loader2, MessageSquarePlus, Play, RefreshCw, RotateCcw, ShieldAlert, UserRoundPlus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import {
  acknowledgeOperationalIncidentApi, assignOperationalIncidentApi, closeOperationalIncidentApi, createOperationalCommunicationApi,
  createOperationalTaskApi, escalateOperationalIncidentApi, getOperationalIncidentApi, getOperationalTripApi,
  getOperationsCoordinatorsApi, reopenOperationalIncidentApi, resolveOperationalIncidentApi, startOperationalIncidentApi
} from '../../../../services/api.js';
import CommunicationFormModal from '../components/CommunicationFormModal.jsx';
import OperationsActionDialog from '../components/OperationsActionDialog.jsx';
import OperationsStatusBadge from '../components/OperationsStatusBadge.jsx';
import TaskFormModal from '../components/TaskFormModal.jsx';
import { formatOperationsDate, formatOperationsWindow } from '../helpers/operationsFormatters.js';

export default function OperationalIncidentDetail() {
  const { incidentId } = useParams(); const [data, setData] = useState(null); const [trip, setTrip] = useState(null); const [coordinators, setCoordinators] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [dialog, setDialog] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await getOperationalIncidentApi(incidentId); setData(response.data); const tripId = response.data.incident.operationalTripId?._id || response.data.incident.operationalTripId; const [tripResponse, people] = await Promise.all([getOperationalTripApi(tripId), getOperationsCoordinatorsApi()]); setTrip(tripResponse.data); setCoordinators(people.data || []); } catch (requestError) { setError(requestError.message || 'Unable to load the incident.'); } finally { setLoading(false); } }, [incidentId]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (key, action) => { setBusy(key); setError(''); try { await action(); await load(); } catch (requestError) { setError(requestError.message || 'Unable to update the incident.'); throw requestError; } finally { setBusy(''); } };
  if (loading && !data) return <div className="flex min-h-72 items-center justify-center rounded-xl border border-slate-200 bg-white text-sm text-slate-500"><Loader2 className="mr-2 animate-spin" size={18}/>Loading incident…</div>;
  if (!data) return <div className="rounded-xl border border-rose-200 bg-white p-8 text-center"><AlertTriangle className="mx-auto text-rose-600"/><h1 className="mt-3 font-semibold">Incident could not be loaded.</h1><p className="mt-2 text-sm text-slate-600">{error}</p></div>;
  const { incident, communications, tasks } = data; const tripId = incident.operationalTripId?._id || incident.operationalTripId;
  return <div className="space-y-5"><header className={`rounded-xl border bg-white p-5 shadow-sm sm:p-6 ${incident.severity === 'CRITICAL' && ['OPEN','IN_PROGRESS'].includes(incident.status) ? 'border-rose-300' : 'border-slate-200'}`}><Link to="/staff/operations/issues" className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-600 hover:text-slate-950"><ArrowLeft size={15}/>Issues &amp; Emergencies</Link><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-mono text-xs font-semibold uppercase tracking-wide text-rose-700">{incident.incidentCode}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{incident.title}</h1><p className="mt-2 text-sm text-slate-600">{incident.contextSnapshot?.title} · {formatOperationsWindow(incident.contextSnapshot)}</p><div className="mt-3 flex flex-wrap gap-2"><OperationsStatusBadge value={incident.severity}/><OperationsStatusBadge value={incident.status}/><OperationsStatusBadge value={incident.escalation?.status}/></div></div><button type="button" onClick={load} disabled={loading} className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm font-semibold text-slate-700"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/>Refresh</button></div>
    <div className="mt-5 flex flex-wrap gap-2">{incident.status === 'OPEN' && <button disabled={busy} onClick={() => mutate('start', () => startOperationalIncidentApi(incident._id))} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white"><Play size={15}/>Start work</button>}{['OPEN','IN_PROGRESS'].includes(incident.status) && <><button disabled={busy} onClick={() => setDialog({ type: 'escalate' })} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-rose-200 px-4 text-sm font-semibold text-rose-700"><ShieldAlert size={15}/>Escalate</button><button disabled={busy} onClick={() => setDialog({ type: 'resolve' })} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white"><CheckCircle2 size={15}/>Resolve</button></>}{incident.escalation?.status === 'ESCALATED' && <button disabled={busy} onClick={() => mutate('ack', () => acknowledgeOperationalIncidentApi(incident._id))} className="min-h-10 rounded-lg border border-amber-200 px-4 text-sm font-semibold text-amber-800">Acknowledge escalation</button>}{incident.status === 'RESOLVED' && <button disabled={busy} onClick={() => mutate('close', () => closeOperationalIncidentApi(incident._id))} className="min-h-10 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white">Close incident</button>}{['RESOLVED','CLOSED'].includes(incident.status) && <button disabled={busy} onClick={() => setDialog({ type: 'reopen' })} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700"><RotateCcw size={15}/>Reopen</button>}<button onClick={() => setDialog({ type: 'communication' })} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700"><MessageSquarePlus size={15}/>Log customer update</button><button onClick={() => setDialog({ type: 'task' })} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700"><UserRoundPlus size={15}/>Create follow-up task</button></div></header>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Summary</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700">{incident.description}</p><dl className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2">{[['Type',incident.incidentType.replaceAll('_',' ')],['Scope',incident.scope.replaceAll('_',' ')],['Reported',formatOperationsDate(incident.reportedAt)],['Reported by',incident.reportedBy?.name || 'Staff'],['Service',incident.serviceSnapshot?.title || 'Not linked'],['Vendor',incident.linkedVendorId?.name || incident.serviceSnapshot?.vendorName || 'Not linked']].map(([label,value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-800">{value}</dd></div>)}</dl></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Actions Taken &amp; Resolution</h2><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{incident.actionTaken || 'No running action note recorded.'}</p>{incident.resolutionSummary && <div className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Resolution</p><p className="mt-2 text-sm text-emerald-950">{incident.resolutionSummary}</p></div>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Timeline</h2><div className="mt-4 space-y-4 border-l border-slate-200 pl-4">{[...(incident.history || [])].reverse().map((event, index) => <div key={`${event.action}-${event.at}-${index}`}><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{event.action.replaceAll('_',' ')}</p><span className="text-xs text-slate-400">{formatOperationsDate(event.at)}</span></div>{event.note && <p className="mt-1 text-sm text-slate-600">{event.note}</p>}<p className="mt-1 text-xs text-slate-400">{event.actorName || 'Staff'}{event.fromStatus && event.toStatus ? ` · ${event.fromStatus} → ${event.toStatus}` : ''}</p></div>)}</div></section></div>
      <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Ownership</h2><label className="mt-4 block text-sm font-medium text-slate-700">Assigned Staff<select value={incident.assignedTo?._id || ''} disabled={busy === 'assign'} onChange={(event) => mutate('assign', () => assignOperationalIncidentApi(incident._id, event.target.value))} className="mt-1.5 min-h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"><option value="">Unassigned</option>{coordinators.map((person) => <option key={person._id} value={person._id}>{person.name} · {person.role}</option>)}</select></label><Link to={`/staff/operations/trips/${tripId}?tab=issues`} className="mt-4 inline-flex text-sm font-semibold text-emerald-700">Open journey issues →</Link></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Customer Communication</h2>{communications.length ? <div className="mt-3 space-y-3">{communications.map((entry) => <div key={entry._id} className="rounded-lg bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><OperationsStatusBadge value={entry.direction}/><span className="text-xs text-slate-400">{formatOperationsDate(entry.occurredAt)}</span></div><p className="mt-2 text-sm font-medium text-slate-800">{entry.summary}</p><p className="mt-1 text-xs text-slate-500">{entry.channel.replaceAll('_',' ')} · logged by {entry.loggedBy?.name || 'Staff'}</p></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No customer update linked yet.</p>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Follow-up Tasks</h2>{tasks.length ? <div className="mt-3 space-y-2">{tasks.map((task) => <div key={task._id} className="rounded-lg border border-slate-200 p-3"><div className="flex justify-between gap-2"><p className="text-sm font-medium text-slate-800">{task.title}</p><OperationsStatusBadge value={task.status}/></div><p className="mt-1 text-xs text-slate-500">{task.assignedTo?.name || 'Unassigned'} · due {formatOperationsDate(task.dueAt)}</p></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No follow-up tasks.</p>}</section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Documents</h2>{incident.documents?.length ? <div className="mt-3 space-y-2">{incident.documents.map((document) => <a key={document.documentId} href={document.secureUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg border border-slate-200 p-3 text-sm font-medium text-slate-700"><span className="inline-flex items-center gap-2"><FileText size={15}/>{document.title}</span><ExternalLink size={14}/></a>)}</div> : <p className="mt-3 text-sm text-slate-500">No incident evidence attached.</p>}</section></aside></div>
    {dialog?.type === 'escalate' && <OperationsActionDialog title="Escalate incident" description="This is an internal escalation record; it does not send a notification." label="Escalation note" placeholder="Why does this need elevated attention?" confirmLabel="Escalate" dangerous onClose={() => setDialog(null)} onConfirm={(note) => mutate('escalate', () => escalateOperationalIncidentApi(incident._id, note))}/>}
    {dialog?.type === 'resolve' && <OperationsActionDialog title="Resolve incident" label="Resolution summary" placeholder="What was done and what is the verified outcome?" confirmLabel="Mark resolved" onClose={() => setDialog(null)} onConfirm={(value) => mutate('resolve', () => resolveOperationalIncidentApi(incident._id, value))}/>}
    {dialog?.type === 'reopen' && <OperationsActionDialog title="Reopen incident" label="Reason" placeholder="Why is further operational work required?" confirmLabel="Reopen" onClose={() => setDialog(null)} onConfirm={(reason) => mutate('reopen', () => reopenOperationalIncidentApi(incident._id, reason))}/>}
    {dialog?.type === 'communication' && trip && <CommunicationFormModal bookings={trip.bookings} services={trip.services} incidents={[incident]} tasks={tasks} defaultIncidentId={incident._id} onClose={() => setDialog(null)} onSave={(payload) => mutate('communication', () => createOperationalCommunicationApi(tripId, payload))}/>}
    {dialog?.type === 'task' && trip && <TaskFormModal coordinators={coordinators} services={trip.services} incidents={[incident]} bookings={trip.bookings} defaultIncidentId={incident._id} onClose={() => setDialog(null)} onSave={(payload) => mutate('task', () => createOperationalTaskApi(tripId, payload))}/>}
  </div>;
}
